### DISCUSSION TITLE
Component Partials

### DISCUSSION THREAD

**Discussion by doostinharrell** [decaporg/decap-cms#5917] [Ideas]
I've been using Netlify CMS to build page layouts for a client recently and I really am enjoying how simple and powerful this basic CMS is.  However, as I've been building complicated collections I have ran into a few limitations where I think things could be improved.

I have several collections that have common components (ie: a landing page has a gallery and so does a service page for example).  It would be awesome if we could load in yml partials rather than duplicating common configuration.

Here is an example of what I'm thinking...

**Possible Folder Structure:**
`
config.yml
-- /components/heading.yml
-- /components/gallery.yml
`

**Possible Yaml Structure:**
```
collections:
  - name: landing_page
    label: Landing Page(s)
    identifier_field: label
    folder: "content/landing-pages"
    create: true
    editor:
      preview: false
    fields:
      - label: Components
          label_singular: component
          name: components
          widget: list
          types:
            - label: Heading
               name: heading
               config: 
                 import: components/heading.yml
            - label: Gallery
               name: gallery
               config:
                 import: components/gallery.yml
```
