### DISCUSSION TITLE
Config Errors: config must have required property ‘media_folder’

### DISCUSSION THREAD

**Discussion by RTiwary** [decaporg/decap-cms#6320] [Q&A]
Hey, I'm getting this error and haven't been able to diagnose it so far (Using NextJS + Netlify):
```
**Config Errors:**

config must have required property 'media_folder' 
config must have required property 'media_library' 
config must match a schema in anyOf

Check your config.yml file.
```
No response on the netlify forums as of yet. I checked out the other answers which say to check indentation and that the media_folder field is there (which it should be), but neither were able to fix. This is my config.yml file:
```
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public"
media_library:
   name: uploads
publish_mode: editorial_workflow

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blogPosts" # The path to the folder where the raw posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Page Title", name: "page_title", widget: "string"}
      - {label: "Meta Description", name: "meta_description", widget: "text"}
      - {label: "Article Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
```

My admin folder is inside my /public folder (which is at my project root) and it has the config.yml file and the index.html file (Exact same as docs). Can send more info if this isn't enough – would appreciate any help! Thanks 😁
