### DISCUSSION TITLE
Conditionally show/hide fields

### DISCUSSION THREAD

**Discussion by onweru** [decaporg/decap-cms#6733] [Q&A] [answered]
Is it possible to show a field only if a sibling field is set to a specific value? For example 👇🏼, I'd like to show the `title` field only when `show` is set to `true`.

```yaml
fields: [
   {
    widget: "boolean",
    name: "show",
    label: "Show section"
  }
  {
    widget: "string",
    name: "title",
    label: "Title"
  },
]
```
