### DISCUSSION TITLE
Custom Logo not loading

### DISCUSSION THREAD

**Discussion by pxrpl** [decaporg/decap-cms#6787] [Q&A]
I added a custom panel logo, and it does not replace the netlify cms one. Please help me, heres my code

```
backend:
  name: git-gateway
  branch: main 
  logo_url: /images/banner.svg

media_folder: "src/images/posts"
public_folder: "/images/posts"

editor:
  preview: true

stylesheets:
  - /src/css/main.css
  - /src/css/syntax.css

collections:
  
     - name: "blog"
       label: "Blog"
       folder: "src/posts"
       create: true
       slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
       fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "date" }
          - { label: "Preview Image", name: "previewImage", widget: "image", value_type: "string", default: "", media_library: { config: { fileMeta: [{ media_folder: "src/images/posts", public_folder: "/images/posts" }], allow_multiple: false }, enabled: true }, hint: "Enter the path to the preview image. Make sure to remove 'src/' from the path.", required: false, value_template: '{{ "/images/posts/" | concat: value | replace: "src/", "" | url_encode }}' }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Post URL", name: "postUrl", widget: "string", default: "{{ page.url | url }}" }
          - { label: "Body", name: "body", widget: "markdown" }

theme:
  mode: dark
```

heres the repo. [repo](https://github.com/pxrpl/blog)

**Comment by martinjagodic** [comment]
Your `logo_url` is in the `backend` object but should be on the root. Docs: https://decapcms.org/docs/configuration-options/#custom-logo

**Reply by pxrpl** [reply]
In the docs there is no object called root

**Reply by martinjagodic** [reply]
The `root` refers to the base of the file. For example, `backend`, `collections`, `media_folder` are the first level items of the configuration, and so is `logo_url`.

**Reply by pxrpl** [reply]
Ok, so I have to put it at the top of the file, so it’s not inside any collection?

**Reply by martinjagodic** [reply]
Yes, instead of 
```yaml
backend:
  name: git-gateway
  branch: main 
  logo_url: /images/banner.svg
```
do this
```yaml
logo_url: /images/banner.svg
backend:
  name: git-gateway
  branch: main 
```
