### DISCUSSION TITLE
TypeError: Cannot read properties of null (reading 'getIn')

### DISCUSSION THREAD

**Discussion by Kenjinful** [decaporg/decap-cms#6790] [Q&A] [answered]
**Describe the bug**
When attempting to add a new object to a list widget, The error in the title is thrown.

**To Reproduce**
1. Use the collections setup listed in the CMS configuration section
2. Create a new entry in the "products" collection
3. In the "variations" list widget, click "Add variations"
4. The error should appear afterward

**Expected behavior**
A new object is added to the list widget

**Applicable Versions:**
 - Netlify CMS version: `netlify-cms-app@2.15.72`
 - Git provider: `proxy`
 - Browser version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

**CMS configuration**
```yaml
backend:
  name: proxy
  proxy_url: *Removed*
local_backend: true
media_folder: static/img
public_folder: /img
site_url: *Removed*
display_url: *Removed*
collections:
  - name: product-categories
    identifier_field: name
    label: Product Categories
    label_singular: Product Category
    folder: src/collections/shop/categories
    create: true
    path: "{{slug}}/index"
    editor:
      preview: false
    fields:
      - label: Name
        name: name
        widget: string
      - label: Slug
        name: slug
        widget: string
    publish: true
    type: folder_based_collection
    media_folder: ""
    public_folder: ""
    sortable_fields:
      - name
      - name
    view_filters: []
    view_groups: []
  - name: products
    identifier_field: name
    label: Products
    label_singular: Product
    folder: src/collections/shop/products
    create: true
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    fields:
      - label: Category
        name: product-category
        widget: relation
        collection: product-categories
        search_fields:
          - name
        value_field: "{{fields.slug}}"
        display_fields:
          - name
      - label: Name
        name: name
        widget: string
      - label: Price
        name: price
        widget: number
        value_type: float
      - label: Description
        name: description
        widget: markdown
      - label: Variations
        name: variations
        widget: list
        summary: "{{summary}}"
        collapsed: false
        field:
          label: Variation
          name: variation
          widget: object
          summary: "{{fields.name}}"
          collapsed: true
          fields:
            - label: Name
              name: name
              widget: string
            - label: Variation Names
              name: variation-names
              widget: list
              summary: "{{fields.variation-name}}"
              collapsed: true
              field:
                label: Variation Name
                name: variation-name
                widget: string
      - label: Image Gallery
        name: image-gallery
        widget: list
        summary: "{{fields.image}}"
        collapsed: false
        field:
          label: Image
          name: image
          widget: image
    publish: true
    type: folder_based_collection
    sortable_fields:
      - name
      - name
      - description
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**
After testing, this bug only occurs if the object widget "variation" has collapsed set to true. If set to false, no error occurs.
