### DISCUSSION TITLE
Use custom date field instead of built-in template tags?

### DISCUSSION THREAD

**Discussion by nick-mon1** [decaporg/decap-cms#6806] [General]
Hello, I have content that is future-dated for upcoming events. Our current config uses the built template date tags 

```
path: "{{year}}/{{month}}/{{slug}}"
```

Is it possible to use a field from the collection instead of the built in template tags like this?

```
 path: "{{fields.date | date('YYYY-MM')}}/{{slug}}"
```

This would set the path to the date the user creates versus the creation date.

Maybe this [summary string template transformations](https://decapcms.org/docs/beta-features/)?

The content date field is a datetime type.

Collection field to reference in `path` for content type:
```
- label: "Start Date/Time"
name: "date"
widget: "datetime"
dateFormat: "YYYY-MM-DD" # e.g. 2021-11.23
timeFormat: "HH:mm" # e.g. 21:00
format: "YYYY-MM-DD HH:mm:00 -0500"
hint: "The start date and time of the event (Note: uses a 24hr clock, e.g. 13:00)"
```

**Comment by nick-mon1** [comment]
Updated my post with the following new code:

`path: "{{date | date('YYYY')}}/{{date | date('MM')}}/{{date | date('YYYY-MM-DD')}}-{{title}}"`

This outputs a filepath and filename:

`cms/future_events/2023-07-28-10-11-00-0500/2023-07-28-10-11-00-0500-test-future-events-4`

But I was expecting it to format like this:

`cms/future_events/2023/07/2023-07-28-test-future-events-4`

Why is `date | date('YYYY')` not formatting just the year?


**config.yml**

```
    name: "future_events"
    label: "Future Events"
    label_singular: "Future Event"
    description: "This page will help create a new event on Digital.gov"
    folder: "content/events"
    summary: "{{title}} ({{year}}-{{month}}-{{day}})"
    # path: "{{date | date('YYYY')}}/{{date | date('MM')}}/{{date | date('YYYY')}}-{{date | date('MM')}}-{{date | date('DD')}}-{{title}}"
    path: "{{date | date('YYYY-MM')}}/{{date | date('YYYY-MM-DD')}}-{{title}}"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "event/{{year}}/{{month}}/{{day}}/{{title}}"
    preview_path_date_field: "start_date"
    fields:
      - label: "Event Title"
        name: "title"
        widget: "string"
        hint: "Short, topical, no acronyms."
        required: false
      - label: "Start Date/Time"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 2021-11.23
        timeFormat: "HH:mm" # e.g. 21:00
        format: "YYYY-MM-DD HH:mm:00 -0500"
        hint: "The start date and time of the event (Note: uses a 24hr clock, e.g. 13:00)"
      - label: "End time"
        name: "end_date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 2021-11.23
        timeFormat: "HH:mm" # e.g. 21:00
        format: "YYYY-MM-DD HH:mm:00 -0500"
        hint: "The end date and time of the event (Note: uses a 24hr clock, e.g. 14:00)"
```
