### DISCUSSION TITLE
Cloudinary config doesn't appear to be working

### DISCUSSION THREAD

**Discussion by derekjohnson** [decaporg/decap-cms#6814] [Q&A]
I'm having a bit of trouble with Cloudinary, in that the only part of the config that appears to be working is the `name`, `cloud_name`, and `api_key`.

Whenever I use the transformations in the docs at https://decapcms.org/docs/cloudinary/ they don't work, and the URL is the original image at the original size.

```yml
media_library:
  name: cloudinary
  config:
    cloud_name: madeupname
    api_key: 1234567890123
    default_transformations:
      - - fetch_format: auto
          width: 650
          quality: auto
          crop: scale
```

Whenever I turn on name only I still get the full URL.

```yml
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: madupname
    api_key: 1234567890123
```

I opened a ticket with Cloudinary and they can't see anything, so here now to see what I've missed.
