### DISCUSSION TITLE
Use decap cms without netlify on self-hosted

### DISCUSSION THREAD

**Discussion by njfamirm** [decaporg/decap-cms#6822] [Q&A] [answered]
hi
I'm create self-hosted hugo website, that's use decap
but when i want to login with github, that's says

```
No Auth Provider Found
Make sure you've configured the API credentials for Github from the Access part of your Netlify site dashboard.
```
```
backend:
  name: github
  branch: main
  repo: njfamirm/hugo-demo
```

why this happen, i can't solve based docs

**Comment by luksak** [comment, marked as answer]
You'll need to specify a `base_url` for your oauth provider:

```
backend:
  name: github
  branch: main
  repo: njfamirm/hugo-demo
  base_url: 'https://oauth.example.com'
```

In case you don't have a oauth provider, you'll need to create one first: https://decapcms.org/docs/external-oauth-clients/

I use this one: https://github.com/vencax/netlify-cms-github-oauth-provider
