### DISCUSSION TITLE
API_ERROR: tree.path contains a malformed path component

### DISCUSSION THREAD

**Discussion by tattooseoul** [decaporg/decap-cms#6825] [Q&A]
When I try to create a new post, I'm getting the following error message:

> API_ERROR: tree.path contains a malformed path component

https://github.com/decaporg/decap-cms/assets/26388798/904bf3e8-92ae-44fe-889d-b7336640fe5a

```
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}{{slug}}" # Filename template, e.g., DD-MM-YYYY-title.md
    nested:
      depth: 100 
    path: "{{filename}}/index"  
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    folder: "content/page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    nested:
      depth: 100 
    path: "{{filename}}/index" 
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```
