### DISCUSSION TITLE
Is there a way to manage content in a separate repo?

### DISCUSSION THREAD

**Discussion by mare-cat** [decaporg/decap-cms#6853] [Q&A]
Is it possible to operate the following setup:
PKCE authorization to a repository with content only which itself functions as a submodule in the actual CMS repo.

```
backend:
  name: gitlab
  repo: foobar/decapcms-content-only
  auth_type: pkce
```

To accomplish the build process I would go with webhooks / integrations and API triggers:

- https://docs.gitlab.com/ee/user/project/integrations/webhooks.html
- https://docs.gitlab.com/ee/ci/triggers/
