### DISCUSSION TITLE
Nested fields in Hugo data files not working?

### DISCUSSION THREAD

**Discussion by 1xn** [decaporg/decap-cms#6865] [Q&A] [answered]
Hello! Just got my first decapCMS running and I have run into an issue, I was using Forestry before and it was working fine.

I have a layout in Hugo which uses a lot of nested fields in the data about.yml files.

Example:

```
company:
   enable: true
   title: company
   text: bla bla 
partnerLogos:
   -logo: images/logos/1.png
    link: "https://example.com"
   -logo: images/logos/2.png
    link: "https://example.com"
   -logo: images/logos/png
    link: "https://example.com"
```
I want to access them like this using the yaml dot notation for nested fields:

```
fields: 
   - {label: "Company Enable", name: "company.enable", widget: "boolean"}
   - {label: "Company Image", name: "company.title", widget: "string"}
   - {label: "Company Title", name: "company.text", widget: "string"}
```
And im figuring out it doesn't work with nested fields, the only solution is to make them not nested like company_enable, company_title...

Also for the Logos example, im using a loop inside Hugo, so for each logo in partnerLogos do `<img src="...">`

Anyone figured out if nested fields are possible at all in the data files so I dont have to rewrite my layout ?

Thank you!
