### DISCUSSION TITLE
Collection of files has a files

### DISCUSSION THREAD

**Discussion by naturedamends** [decaporg/decap-cms#6931] [Q&A]
I can get a collection of files, but how about a file which has other files

```
  - label: Pages
    name: about
    files:
      - label: "About"
        name: About
        file: content/about.md
        fields:
          - {label: "layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "draft", name: "draft", widget: "boolean", required: false}
          - {label: "title", name: "title", widget: "string"}
          - {label: "publish date", name: "date", widget: "datetime"}
          - {label: "description", name: "description", widget: "string"}
          - {label: "body", name: "body", widget: "markdown"}
      - label: "Pricing"
        name: Pricing
        file: content/pricing.md
        fields:
          - {label: "layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "draft", name: "draft", widget: "boolean", required: false}
          - {label: "title", name: "title", widget: "string"}
          - {label: "publish date", name: "date", widget: "datetime"}
          - {label: "description", name: "description", widget: "string"}
          - {label: "body", name: "body", widget: "markdown"}
          - files:
             - file: "somefile.yaml"
                fields: ...
```
