### DISCUSSION TITLE
List of maps inside a object

### DISCUSSION THREAD

**Discussion by naturedamends** [decaporg/decap-cms#6972] [Q&A]
I'm trying to create a list of maps, the following uses the wrong keys, ie `[[params.ananke_socials.map]]` instead of `[[params.ananke_socials]]` 

my attempt is 
```
          - label: params
            name: params
            widget: object
            fields:
              - label: Socials
                name: "ananke_socials"
                widget: list
                fields: 
                  - label: "map"
                    widget: object
                    fields:
                      - {label: Name, name: name, widget: string}
                      - {label: URL, name: url, widget: string}
```

I want to create objects like this in my TOML files

```
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
```

I assume that doing the following would work. but Then i'm not able to have other object keys within the params

```
          - label: params
            name: params
            widget: list
            field:
              label: "map"
              name: "ananke_socials"
              widget: object
              fields:
                - {label: Name, name: name, widget: string}
                - {label: URL, name: url, widget: string}
```

Iv also tried https://github.com/decaporg/decap-cms/issues/596

And the solution always appends the list element name to 

[params.list.elementname]
