### DISCUSSION TITLE
405 error from Gitea auth backend?

### DISCUSSION THREAD

**Discussion by mattcen** [decaporg/decap-cms#6984] [Q&A] [answered]
Hi folks,

Not sure if this is a bug or user error, but I have this in my `config.yml`:
```yaml
backend:
  name: gitea
  repo: mattcen/hugo-cms-test # Path to your Gitea repository
  app_id: REDACTED # The Client ID provided by Gitea
  api_root: https://codeberg.org/api/v1 # API URL of your Gitea instance
  base_url: https://codeberg.org # Root URL of your Gitea instance
  # optional, defaults to master
  branch: main
```

And am using the latest beta release in my `index.html`:
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex" />
  <title>Content Manager</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Decap CMS -->
  <script src="https://unpkg.com/decap-cms@3.1.0-beta.1/dist/decap-cms.js"></script>
</body>
</html>
```

But when I try to authenticate using Gitea/Forgejo, after the redirect back from https://codeberg.org/login/oauth/authorize, Decap tries an OPTIONS request to https://codeberg.org/login/oauth/access_token, and gets back a 405 from Forgejo, which seems to be a CORS issue, but even when trying the same with my own Forgejo instance and playing around with its [CORS settings](https://forgejo.org/docs/latest/admin/config-cheat-sheet/#cors-cors), I can't get it to work.

Anybody able to enlighten me?

(It does look like the Gitea backend is quite new so perhaps it's just not quite ready for prime time?)
