### DISCUSSION TITLE
Decap i18n with Hugo?

### DISCUSSION THREAD

**Discussion by majdal** [decaporg/decap-cms#7291] [Q&A] [answered]
I'm trying to use Decap with my multilingual site built using Hugo (using hugo-blox). I followed the directions [here](https://docs.hugoblox.com/getting-started/cms/decap/), but they don't include specific directions for translating content. 

The [i18n section](https://decapcms.org/docs/i18n/) of the Decap docs seems to be missing something. Mainly, I'm having trouble reconciling the directory structure that Decap expects with the one that Hugo(-blox) expects. There are 3 options available for translating content using Decap, 
```
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
```

All of these seem to be inconsistent with what Hugo expects, which is `<content>/<locale>/<content type>`. I have tried so many different approaches, but I can't get the translation/multilingual interface to appear. 

The extensions part of my `params.yaml` file looks like this (almost identical to the one suggested by Decap docs):

```
extensions:
  decap_cms:
    local_backend: true
    publish_mode: editorial_workflow
    branch: main
    i18n:
      structure: multiple_folders
      locales: [en, ar]
      default_locale: ar

    collections:
      - name: projects
        label: Projects
        folder: content/en/project
        create: true
        i18n: true
        fields:
          - label: Title
            name: title
            widget: string
            i18n: true
          - label: Date
            name: date
            widget: datetime
            i18n: duplicate
          - label: Body
            name: body
            widget: markdown
```
Any thoughts on what I should do here? Many thanks!

**Comment by martinjagodic** [comment]
In my experience, it's best to use the `<folder>/<slug>.<locale>.<extension>`, which is supported both by Hugo and Decap.

If you want to use `<content>/<locale>/<content type>`, that would be the `multiple_folders ` option.

**Reply by majdal** [reply]
I tried that, but I can't tell how the Decap interface should look like for the multiple_files option. There's nowhere no the UI that indicates language as a metadata option.

Let's say I want to make all the content under the content/project available in both ar and en locales. How should my configuration look like?

**Reply by janealsh** [reply]
I'm dealing with something similar, and my params.yaml file looks almost identical as well

**Reply by martinjagodic** [reply, marked as answer]
@majdal here is an example configuration

```yaml
# other root config here (backend, media_library etc.)

i18n:
  structure: multiple_files
  locales: [en, ar]

collections:
  - name: projects
    label: Projects
    label_singular: project
    folder: content/projects
    i18n: true
    create: true
    fields: [
      {name: title, widget: string, i18n: true},
      {name: image, widget: image, i18n: duplicate},
    ]
```

And this is how the UI should look like:

![hugo-decap-example](https://github.com/user-attachments/assets/b5693a08-ef43-4066-bdda-25abbb2a7a2d)

**Reply by majdal** [reply]
That's it! Ok, thank you so much.

**Reply by infredder** [reply]
I have the exact same setup. But I cannot get my head around single file collection?

```
  - name: "research_clinic_page"
    label: "Research Clinic (Index Page)"
    files:
      - name: "research_clinic_index"
        label: "Research Clinic Index Page"
        file: "content/research/research_clinic/_index.en.md"
        i18n: true
        fields:
              .....
```

In the decap CMS I can actually see the research clinic but I cannot translate it. 

Any ideas?
