### DISCUSSION TITLE
Required Fields within Optional Object

### DISCUSSION THREAD

**Discussion by mirhamasala** [decaporg/decap-cms#7302] [General]
In the following setup, the object is optional, but I want the fields inside the object to be required. However, this doesn’t seem to be possible. Am I misunderstanding the intended behavior? Is this functioning as expected?

```
- name: "external-link"
  label: "External Link URL"
  widget: "object"
  required: false
  collapsed: true
  fields:
    - name: "url"
      label: "URL"
      widget: "string"
    - name: "text"
      label: "Text"
      widget: "string"
      required: false
      default: "View Event Details"
```

![CleanShot 2024-10-10 at 11 46 47@2x](https://github.com/user-attachments/assets/6bf9198f-3a08-42e0-985a-114df68534af)
