### DISCUSSION TITLE
Zola Static Site Generator: Content does not load in admin view

### DISCUSSION THREAD

**Discussion by dcrck** [decaporg/decap-cms#7324] [Q&A] [answered]
Hi there! I'm using Netlify to host my [Zola](https://getzola.org) static site. I'm able to log into the admin console with Netlify Identity, but the collections aren't showing up as expected.

Here's my folder structure:

```
my-site
├── config.toml
├── content
│   ├── _index.md
│   ├── about
│   │   └── _index.md
│   ├── case-studies
│   │   ├── _index.md
│   │   ├── item-1.md
│   │   ├── item-2.md
│   │   └── item-3.md
│   ├── contact
│   │   └── _index.md
│   └── news
│       ├── _index.md
│       ├── item-1.md
│       ├── item-2.md
│       └── item-3.md
├── static
│   ├── admin
│   │   ├── config.yml
│   │   └── index.html
│   ├── ...
```

and here's the relevant part of the `config.yml`:

```
collections:
  - name: "news"
    label: "News"
    folder: "/content/news"
    create: true
    slug: "{{slug}}"
    format: toml-frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    format: toml-frontmatter
    files:
      - name: "contact"
        label: "Contact Page"
        file: "/content/about/_index.md"
        fields:
          - {label: "Form Title", name: "extra.form_title", widget: string}
          - {label: "Form Description", name: "extra.form_description", widget: string}
          - {label: "Form Email Input Label", name: "extra.form_email_input_label", widget: string}
          - {label: "Form Submit Button Text", name: "extra.form_submit_button_text", widget: string}
```

I have tried removing the leading slashes on the file paths above, but get the same results.

Here's what `/content/about/_index.md` looks like. It only has frontmatter, and the rest of the content is loaded in the template:

```
+++
title = "Contact Us"
template = "contact.html"

[extra]
form_title = "Get in touch"
form_description = "Interested in our product? Want to stay in the loop? Let us know!"

form_email_input_label = "Email"
form_submit_button_text = "Submit"
+++
```

Here's how my collections appear in the CMS:
![image](https://github.com/user-attachments/assets/773d51af-836d-4ba6-8fe9-e73d529bd94b)

And here's the "Contact" page fields not populating as I would expect:
![image](https://github.com/user-attachments/assets/14bd4e52-8a1e-4dd6-a41d-32d3df23d3c7)

Looking at the console window, I'm noticing a lot of 404 requests to routes like:

- `https://my-site.netlify.app/.netlify/git/github/git/trees/master:content%2Fabout`
- `https://my-site.netlify.app/.netlify/git/github/commits?path=content/about/_index.md&sha=master`
- `https://my-site.netlify.app/.netlify/git/github/git/trees/master:content%2Fabout`

This is a public repository under my account. Do I have something configured incorrectly in the config file or in Netlify? What am I doing wrong here? Thanks!

**Comment by dcrck** [comment]
Okay, one of the issues was that decap was using `master` as the main branch instead of `main`, so I fixed that. The `news` collection is showing up, but my custom frontmatter on the `contact` page is still missing. How can I specify this in the config properly?

**Comment by dcrck** [comment, marked as answer]
Okay, turns out I was referencing the wrong page (oops), it should be `content/contact/_index.md`. Also, I need to use the `object` widget for nested fields.

This works:

```
- name: "pages"
    label: "Pages"
    format: toml-frontmatter
    files:
      - name: "contact"
        label: "Contact Page"
        file: "/content/contact/_index.md"
        fields:
          - name: "extra"
            label: "Editable fields"
            widget: object
            fields:
              - {label: "Form Title", name: "form_title", widget: string}
              - {label: "Form Description", name: "form_description", widget: string}
              - {label: "Form Email Input Label", name: "form_email_input_label", widget: string}
              - {label: "Form Submit Button Text", name: "form_submit_button_text", widget: string}
```
