### DISCUSSION TITLE
How do you upload multiple images in the `Image` widget?

### DISCUSSION THREAD

**Discussion by charludo** [decaporg/decap-cms#7459] [General]
I have one configured as follows:
```yaml
      - label: "Gallerie"
        name: "gallery"
        hint: "[gallery]!!(gallery)"
        widget: "image"
        choose_url: false
        allow_multiple: true
        media_library:
          config:
            multiple: true
```

And I was expecting that I would be able to click "Upload", and then choose multiple images in the system file picker dialogue. Am I missing something?

Edit: actually, even after uploading them one by one, I cannot find a way to select multiple already uploaded images in the widget. What am I doing wrong?
