### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by TylerBarnes** [decaporg/decap-cms#1191]
Hey there,
I've been reading a lot about netlify, netlifycms and jamstack. I'm doing some research / dabbling with the intent of making a proposal to my boss to switch from building wordpress sites to static sites. Netlifycms looks like a great option to me since it's minimal, beautiful, open source, and we could use gatsby with it. 
I've been trying to find what the recommended way is to set up menus but I can't really see how. I assume I would just use a collection with a list field but I was hoping for something a little more robust. forestry.io has a menus page built in where you can choose from a dropdown list to add menu items. You can also drag items horizontally to nest them as sub menu items.
Is there something like this for netlifycms or are there future plans for it?

**Comment by erquhart** [comment]
That depends heavily on the static site generator. Gatsby doesn't really have a blessed method for menu creation, but the Lumen starter has one approach using site metadata in the Gatsby config file ([source](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/c27d5ba0137ca95699808ff3fa9d028f470b294c/gatsby-config.js#L8-L21)). You could probably do what their doing, but using a data file (yaml, json, etc), and then querying that for your menu.

**Comment by inwardmovement** [comment]
Are there plans to allow edition of navigations/menus (and generally every editable content) in the NetlifyCMS so it can be a "full" CMS and not just a "minimalistic" one?

Or any guidelines to adding this feature to NetlifyCMS for the most popular static site generators?

**Comment by tomrutgers** [comment]
@inwardmovement You can already allow editing navigations and menus through the CMS, but you have to set it up the way you want to. It's impossible to standardize such a thing because it depends so heavily on which SSG you're using, even the most popular have a lot of differences between them. 

An example from one of the [starters](https://github.com/tomrutgers/middleman-starter-netlify-cms): 

`config.yml`

```yml
collections:
  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
```
`data/settings/navigation.yml`
```yml
    
nav_items: 
  - {label: 'Home', path: '/'}
  - {label: 'Products', path: '/products/'}
  - {label: 'News', path: '/news/'}
```
