### ISSUE TITLE
[feature request] responsive preview options

### ISSUE THREAD

**Issue by zebapy** [decaporg/decap-cms#1358]
It'd be nice if there was a way to set varying breakpoints in `admin.yml` which would create breakpoint previews in the editor. 

My desire for this is kind of weird because my app uses the cms to build html emails without ever publishing the content as web pages. 

Example config could be

```yaml
previewer_breakpoints:
- label: Mobile
  width: 320
- label: Tablet
  width: 768
- label: Desktop
  width: 1024
```
Super rough comp:

![desktop hd](https://user-images.githubusercontent.com/2199845/40005987-45b9dc12-5767-11e8-865e-d88c924c702a.png)

Maybe a way to hide the form would suffice, like you can hide the preview.
