### ISSUE TITLE
Receiving an error while trying to access to the CMS console

### ISSUE THREAD

**Issue by davidberco** [decaporg/decap-cms#2368]
**Describe the bug**
I receive an error while accessing the console
**To Reproduce**
1. I receive the link send by email from netlify
2. In the browser I enter the information (the welcome screen looks different btw)
3. I receive the error:
```
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=t%3A%20invalid_grant%3A%20Invalid%20Password&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```
**Expected behavior**
To access normally to the console
**Applicable Versions:**
 - Netlify CMS version: 2.0.0
 - Git provider: GitHub
 - OS: macOs
 - Browser version: firefox 67.0.1
 - Node.JS version: ---

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

media_folder: "images"

collections:
  - name: "header"
    label: "header"
    files:
    - label: "header"
      name: "header"
      file: "_data/site.yml"
      fields:
      - label: "Header Tagline"
        name: "intro_display"
        widget: "string"

```

**Comment by tomrutgers** [comment]
Try updating to the latest version `2.9.1`

Your indentation seems a bit off as well (nesting of `files` and `fields` properties):
```
collections:
  - name: "header"
    label: "header"
    files:
      - label: "header"
        name: "header"
        file: "_data/site.yml"
        fields:
          - label: "Header Tagline"
            name: "intro_display"
            widget: "string"
```

**Comment by sandiegoscott** [comment]
I'm seeing the same error. Have updated Netlify CMS version.

Expected behavior:
To access normally to the console

Applicable Versions:

- Netlify CMS version: 2.4.2 and 2.9.8-beta.4
- Git provider: GitLab
- OS: macOS
- Browser version: Firefox 70.0 and Chrome 77.0.3865.90
- Node.JS version: ---
- Website builder: Middleman 4.3.5

CMS configuration:

```
backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Headlines
            name: headlines
            widget: object
            fields:
              - {label: Main, name: main, widget: string}
              - {label: Sub, name: sub, widget: string}
          - label: Content
            name: content
            widget: markdown
```

home.yml file:

```
headlines:
  main: Virtual Assistant - Office Support
  sub: Let Us Be Part of Your Team
content: >-
  Office chores keeping you from your work? We look after all the 
  time-consuming administrative details and make you look great in the process.
```
