### ISSUE TITLE
netlify-cms on a gitbook

### ISSUE THREAD

**Issue by deleyva** [decaporg/decap-cms#3134]
I am trying to put in place the netlify-cms in a gitbook project.

## Problem 1

As I started this book without your cms I wasn't able to see the title of entries made by hand previously because they didn't have a frontmatter. I've added it by hand:

### I've added the frontmatter 

![Selección_732](https://user-images.githubusercontent.com/10669244/72983820-86b2f600-3de2-11ea-947c-83502079c13a.png)

### ... and I can see the titles

![Selección_733](https://user-images.githubusercontent.com/10669244/72983901-b235e080-3de2-11ea-8bc6-448b2a555df3.png)

### ... but, when I click on them, I se the following error:

![Selección_730](https://user-images.githubusercontent.com/10669244/72983601-f379c080-3de1-11ea-8118-f7cad379ba66.png)

I've managed to solve it sometimes editing the config.yml but now I'm stuck.

## Problem 2

Gitbook organize content by parsing a SUMMARY.md. ¿How could I get to edit it?

```md
# Summary

## General

* [Motivación](README.md)
* [Dietas](general/dietas.md)

## Wordpress

* [Crear Wordpress para Centro Educativo](WordPress/crear-wordpress-centro-educativo.md)

## Moodle

* [El tema Boost-maker](moodle/maker_boost_theme.md)
* [Final de convocatoria](moodle/final_convocatoria.md)
* [Actualizar Moodle](moodle/actualizar_moodle.md)
* [Extraer funcionarios en prácticas no finalizados](moodle/complecion_funcipracs.md)
* [Selección de tutores](moodle/seleccion_tutores.md)
* [Habilitar clave API y añadir funciones](moodle/api.md)
```

### To summarize

I can't a write new content, neither I can edit old files.

**Applicable Versions:**

 - Netlify CMS version: [^2.0.0]
 - Git provider: [Gitlab]
 - OS: [Ubuntu 18.04]
 - Browser version [Versión 62.0.3202.94 (Build oficial) (64 bits)]

 - Node.JS version: \^10

### **CMS configuration**

```yml
backend:
  name: gitlab
  branch: master # Branch to update (optional; defaults to master)
  repo: catedu/documentacion-catedu
  auth_type: implicit
  app_id: ******************************

media_folder: "/img"
#publish_mode: editorial_workflow
site_url: https://catedu.gitlab.io/documentacion-catedu/
display_url: https://catedu.gitlab.io/documentacion-catedu/
logo_url: https://catedu.gitlab.io/documentacion-catedu/img/logo-catedu-transparent-complete.png

collections:
  - name: "moodle"
    label: "Moodle"
    folder: "/moodle"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
```

### **Index.html**

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Documentación CATEDU</title>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js"></script>
</body>
</html>
```
