### ISSUE TITLE
[stub] HTML pasting issues in markdown widget

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-cms#3437]
Pasting the following into the rich text editor of the markdown widget produces empty blocks:

## Input API

|key                         |required|default|description                                                                                           |
|-----------------|---------|-------|----------------------------------------------------------------|
| `name` |**yes**| |name for internal reference purposes|
| `label` |**yes**| |proper display name for UI|
| `type` ||`"string"`|Type of input mechanism (not necessarily value type, Eg., "select" will be a type|
| `description` |||Longer description|
| `required` ||`false`|Set field as required|
| `default` |||Default value used if none supplied |
| `pattern` |||Regular expression that this string should match. Only applicable to strings.|
| `sensitive` ||`false`|Whether to mask the value to prevent it from being displayed in the logs, CLI, or API.|

Example:

```yml
inputs:
  - name: phone
    label: Twilio Phone Number
    required: true
    pattern: /^([0-9\(\)\/\+ \-]*)$/
    sensitive: true
```
