### ISSUE TITLE
Editing from the CMS adds extraneous apostrophes for Python + Pelican site

### ISSUE THREAD

**Issue by alecbw** [decaporg/decap-cms#3473]
I have a simple static site built on [Pelican](https://blog.getpelican.com/) 

When I first stood it up, I was editing the blog posts in Markdown on my local device and deploying through git push.

I migrated to using the CMS to save and publish articles. This workflow uses the Create PR -> Add Commits -> Merge to master pathway. It also, I believe inadvertently, modifies the date and tag fields to include a leading and trailing single quote mark/apostrophe. 
![image](https://user-images.githubusercontent.com/23533756/77354803-a3937900-6d00-11ea-9756-3e39f9f1de07.png)

This causes my tags/categories to have apostrophes added to the first and last item of the list. This is most apparent when displaying these tags/categories separately:
![image](https://user-images.githubusercontent.com/23533756/77354668-71821700-6d00-11ea-9d1b-55c85987ee89.png)

Included below is my config.yml
```
# Config for Netflix CMS

backend:
  name: github
  repo: alecbw/static_site # My private GH repo
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "content/images" # Media files uploaded from the CMS will be stored here
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" 
    label: "Posts"
    folder: "content/posts"
    sort: "date:desc"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "string", default: "general"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "about"
        file: "content/pages/about.md"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
```

Any thoughts on fixing this? I can git pull to my local device, remove the apostrophes, and redeploy and it will work as normal again. However, once I edit a given article in the CMS again the problem re-starts
