### ISSUE TITLE
Can't publish a blog post "Failed to persist entry: TypeError: r.has is not a function"

### ISSUE THREAD

**Issue by MatteoGauthier** [decaporg/decap-cms#3492]
**Describe the bug**
When i try to publish a blogpost, it don't works.
And my already posted post aren't displayed in the cms interface.
**To Reproduce**
Repo at this time
https://github.com/MattixNow/mattaio-website/tree/4047871fdd6cbf3d631682fe38cd4fbd7e703d44
```
git clone https://github.com/MattixNow/mattaio-website
cd mattaio-website
git checkout 4047871
```

The deploy to netlify

**Expected behavior**
The netlify cms soft should publish the post
**Screenshots**

![image](https://user-images.githubusercontent.com/32040951/77852022-a698d880-71dc-11ea-8607-99734c1d81cc.png)

**Applicable Versions:**

 - Netlify CMS version: 2.10.35
 - Git provider: Github
 - OS: Win10
 - Browser version Chrome 80

 - Node.JS version: v12.14.0

**CMS configuration**
```yaml
backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY" }
      # - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          hint: "Only allows 255 characters",
        }
      - { label: "Body", name: "body", widget: "markdown" }

```
