### ISSUE TITLE
Datetime Widget Displays current Datetime when field is empty

### ISSUE THREAD

**Issue by Undistraction** [decaporg/decap-cms#3679]
**Describe the bug**
I just tried to switch us over from the Date widget to the Datetime widget, however, it appears the Datetime widget will always display the current date/time, even if the field has no value.

This makes it look like the field has a value when it does not and is very confusing for users. 

**To Reproduce**

1. Create a field with a widget type of 'datetime'.
2. Set a default value of `''` or do not set a default value. 

**Expected behavior**
The widget should behave the same as the Date widget, showing a blank field until the field is clicked into. 

**Applicable Versions:**

 - Netlify CMS version: 2.12.11
 - Browser version Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by erezrokah** [comment]
Hi @Undistraction, can you share a config file? I'm using:
```yaml
backend:
  name: test-repo

media_folder: assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    folder: '_posts'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - {
          label: 'Publish Date',
          name: 'date',
          default: '',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
```
And getting:
![image](https://user-images.githubusercontent.com/26760571/80723757-b2dcc200-8b09-11ea-8bbc-86a5234319bd.png)
