### ISSUE TITLE
Jekyll sites don't produce usable branch URLs in editorial workflow

### ISSUE THREAD

**Issue by typhoon2099** [decaporg/decap-cms#3699]
**Describe the bug**
Using Jekyll to build a site using the editorial workflow creates branch subdomains that are not valid and lead to nowhere. This is a problem for Slack notifications as the branch URL is posted, meaning that non-technical users of NetlifyCMS cannot see previews for new content.

**To Reproduce**
1. Create a Jekyll blog
2. NetlifyCMS to it
3. Enable branch-based deploys
4. Enable Slack notifications
5. Create a post

**Expected behavior**
The Slack notification contains a link which can be followed to preview content changes

**Applicable Versions:**

 - Netlify CMS version: 2.10.47
 - Git provider: BitBucket

**CMS configuration**
```
backend:
  name: bitbucket
  repo: *redacted*
  auth_type: implicit
  app_id: *redacted*
publish_mode: editorial_workflow
media_folder: 'jekyll/images/blog'
public_folder: '/images/blog'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'jekyll/_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Category', name: 'category', widget: 'select', options: ['Announcements', 'Clients', 'Development', 'Discussion Point', 'Events', 'Productivity', 'Reviews', 'Security', 'Work Experience'] }
```

**Additional context**
[Discussion of the problem here](https://community.netlify.com/t/cant-access-urls-in-slack-messages-from-draft-deploys/13010/22). I'm not interested in PR deploys, I'm interested in getting a URL in Slack when an editorial branch is created.
