### ISSUE TITLE
Return URL setting after logging in instead of going to homepage 

### ISSUE THREAD

**Issue by srchulo** [decaporg/decap-cms#4184]
**Is your feature request related to a problem? Please describe.**
When I go to site.com/admin/ to login using Netlify Identity, it always returns me to the home page after login, but I went to /admin/ because I wanted to be in Netlify CMS.

**Describe the solution you'd like**
I would love if there was a setting to say what URI to go to after logging in:

```
backend:
  name: git-gateway
  branch: master
  after_login_uri: "/admin/"
```
