### ISSUE TITLE
datetime widget behaves differently between init({config}) and init()

### ISSUE THREAD

**Issue by emileswain** [decaporg/decap-cms#4582]
**Describe the bug**
DateTime format is saved differently when launching admin with config.yml and config.js.

This causes a subsequent error in getStaticProps where the matter parser throws the error (note in comment below i show matter can catch/manage this error when told to), but that doesn't resolve the different behaviour in using config.js and config.yml.
```
SerializableError: Error serializing `.mdx.mdxSource.scope.date` returned from `getStaticProps` in "/[page]".
Reason: `object` ("[object Date]") cannot be serialized as JSON. Please only return JSON serializable data types.
```

I originally configured site with config.yml and it saves content like so 
```
---
slug: ymlserverdate
title: ymlserverdate
date: '2020-11-14'
---
ymlserverdate
```

When load the admin with config.js I noticed that the datetime widget behaves differently in how it saves its content.
```
---
slug: serverDate
title: serverDate
date: 2020-11-14
---
serverDate with config.js
```

Note that the server date is saved as a string when config.yml is used, and as a date when config.js is used.
```
date: 2020-11-14
date: '2020-11-14'
```

**Comments**
I noticed this change as without quotes the getStaticProps() throws up an error trying to parse an object as the date is not a string.

I'm not sure if this is to do with the formating of the parameters in my config.js (see below) and there does not appear to be any documentation covering the differences between a yml or js approach to defining the config.

I hope this is just stupidity on my part messing up the config.js file. 

I might add that i get Nextjs to create an admin page here mysite/admin and i also have the standard admin.html in public/admin/index.html. As such i'm able to test both scenarios from the same netlify deployment.

**Config files**
config.yml 

```
backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow


collections:
  - name: "pages"
    label: "Pages"
    folder: "cms/pages"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "articles"
    label: "Articles"
    folder: "cms/articles"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "AR Label"
        name: "arasset"
        widget: "arasset"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "Body"
        name: "body"
        widget: "markdown"
```
config.js
```
//test-repo
//git-gateway
export default {
    load_config_file: false,
    cms_manual_init: true,
    backend: {
        name: 'git-gateway',
        branch: 'main',
    },
    media_folder: 'public/img',
    public_folder: 'img',
    publish_mode: 'editorial_workflow',
    collections: [
        {
            name: 'pages',
            label: 'Pages',
            folder: 'cms/pages',
            extension: "mdx",
            format: "frontmatter",
            create: true,
            slug: "{{slug}}",
            identifier_field: 'slug',
            summary: "{{title}}",
            fields: [
                {
                    label: 'Slug',
                    name: 'slug',
                    widget: 'string',
                },
                {
                    label: 'Title',
                    name: 'title',
                    widget: 'string',
                },
                {
                    label: "Publish Date",
                    name: "date",
                    widget: "datetime",
                    format: "YYYY-MM-DD",
                    dateFormat: "YYYY-MM-DD",
                    timeFormat: false,
                },
                {
                    label: "Body",
                    name: "body",
                    widget: "markdown",
                },
            ],
        },
        {
            name: 'articles',
            label: 'Articles',
            folder: 'cms/articles',
            extension: "mdx",
            format: "frontmatter",
            create: true,
            slug: "{{slug}}",
            identifier_field: 'slug',
            summary: "{{title}}",
            fields: [
                {
                    label: 'AR Label',
                    name: 'arasset',
                    widget: 'arasset',
                },
                {
                    label: 'Slug',
                    name: 'slug',
                    widget: 'string',
                },
                {
                    label: 'Title',
                    name: 'title',
                    widget: 'string',
                },
                {
                    label: "Publish Date",
                    name: "date",
                    widget: "datetime",
                    format: "YYYY-MM-DD",
                    dateFormat: "YYYY-MM-DD",
                    timeFormat: false,
                },
                {
                    label: "Body",
                    name: "body",
                    widget: "markdown",
                },
            ],
        },
    ],
};
```

In my test i loaded the config.js with the following NextJS admin.tsx
(at this point of time i haven't removed my custom component to see if thats causing any issues)
```

//import { ARAssetControl, ARAssetPreview , ARAssetEditorComponent} from 'netlify-cms-widget-arasset'
import { ARAssetControl, ARAssetPreview , ARAssetEditorComponent} from '../cms/plugins/arasset'
import dynamic from 'next/dynamic';
import config from '../cms/cms-config'

import React from 'react'
//https://medium.com/better-programming/how-to-implement-netlify-cms-with-next-js-4b8721bdec45
const CMS = dynamic(
    () =>
        import('netlify-cms-app').then((cms) => {
            console.log("Initialising cms : Register Component (Widget)");
            // @ts-ignore
            cms.registerWidget('arasset', ARAssetControl, ARAssetPreview);

            console.log("Initialising cms : Register Component (editor)");
            // @ts-ignore
            cms.registerEditorComponent(ARAssetEditorComponent);

            console.log("Initialising cms 3 : Pre init()");

            if (location.hostname === "localhost" || location.hostname === "127.0.0.1")
                config.local_backend = true;

            // @ts-ignore
            cms.init({config});
            console.log("Initialising cms : Post init()");
        }) as any,
    { ssr: false, loading: () => <p>Loading...</p> }
);

const AdminPage: React.FC= () => {
    return <CMS />;
};

export default AdminPage;
```

**To Reproduce**

1. Launch yoursite/admin with standard setup.
2. Create page with a dateTime widget
3. view saved mdx and see date time is saved with single quotes 'date: 2020-11-14'

4. Launch yoursite/admin with custom init() passing in equivelent config object.
5. Create page with a dateTime widget
6. view saved mdx and see date time is saved **without** single quotes date: 2020-11-14

**Expected behavior**
Regardless of config the saved format should be the same.

**Screenshots**
N/A

**Applicable Versions:**

 - Netlify CMS version:
netlify-cms-app 2.9.7
bootstrap.js:54 netlify-cms-core 2.12.2
index.js:27 netlify-cms 2.9.7

 - Git provider: GitHub
 - OS: Windows 10
 - Browser version chrome 22

**CMS configuration**

**Additional context**
