### ISSUE TITLE
[object] Can't use wildcard in a relation field pointing to an object

### ISSUE THREAD

**Issue by loic-roux-404** [decaporg/decap-cms#4674]
Coming from this [netlify forum thread](https://community.netlify.com/t/how-can-i-get-an-object-data-inside-a-relation-widget/19147/4)

### Subject :  

Trying to build these objects fields, it appears we can't use wildcard in `relation` for fetching fields of an `object`.
`*` is only available for `list` field.

```toml
[en]
languageName = "English"
title = "Alouette house"

[fr]
languageName = "Français"
title = "Maison alouette"
```

The corresponding file is the example of what i've tried (check comment) : 

```yml
backend:
  name: git-gateway
  proxy_url: 'http://localhost:8081/api/v1'
  repo: loic-roux-404/hugo-netheme
  squash_merges: true
  use_graphql: true
local_backend: true
media_folder: exampleSite/assets/medias
public_folder: /medias
collections:
  - extension: toml
    files:
      - fields:
          - collection: international
            file: languages
            label: Disable Langs
            name: disable
            display_fields:
              - en.title
            search_fields:
              - en.title # Here i want to use *.title to also target both fr.title and en.title
              - en.languageCode
            value_field: en.languageCode
            widget: relation
        file: exampleSite/config/_default/config.toml
        label: Core hugo config
        name: core
    label: Settings
    media_folder: ../../exampleSite/assets/medias/settings
    name: settings
    public_folder: /medias/settings
  - extension: toml
    label: International configuration
    name: international
    files:
       - file: config/_default/languages.toml
         name: 'languages'
         label: Languages metadatas
         extension: toml
         fields:
            - label: Language metas (French)
              name: fr
              widget: object
              fields:
              - name: languageName
                required: true
                widget: string
              - label: Title
                name: title
                required: true
                widget: string
            - label: Language metas (English)
              name: en
              widget: object
              fields:
                - name: languageName
                  required: true
                  widget: string
                - label: Title
                  name: title
                  required: true
                  widget: string
```

This feature can be useful in some contexts like when we want to build UI for configurations...

For now I can't find alternatives in this context. This config file strictly need this structure for making hugo generates site...
