### ISSUE TITLE
CMS events don't update i18n content values

### ISSUE THREAD

**Issue by wslyvh** [decaporg/decap-cms#4729]
I'm trying to use CMS event listeners with i18n enabled.
I realize both are beta features and might not be in a state that is sufficient for my use-case.

What I'd like to achieve is to automatically translate content from the default lang into the other language(s). I was thinking of:

1. catch a preSave (or prePublish) CMS event, using cms.registerEvents
2. take the data (or certain fields) from the entry using entry.get('data')
3. use an API service (Google translate) to translate these value(s)
4. saving the translated values for the i18n content object using entry.get('data').set('desc', 'translated desc')

I'm able to catch and read all content data for both languages, following the docs at
https://www.netlifycms.org/docs/beta-features/#registering-to-cms-events 

The updates, however, are only saved for the original (en) content.

Here's an example of the event handler

```
CMS.registerEventListener({
    name: 'preSave',
    handler: ({ entry }) => {
        const description = entry.get('data').get('description');
        const descripcion = entry.get('i18n').get('es').get('data').get('description');
        console.log("Current values", description, descripcion);

        return entry.get('i18n').get('es').get('data').set('description', 'Saving my new Spanish description');
    }
});
```

Results of saving my page from the CMS.
![image](https://user-images.githubusercontent.com/25974464/102270761-ae410e80-3f1e-11eb-91c6-9e62822335c7.png)
As you can see, the description is updated on the en/page.md and nothing was added on the es/page.md

For completion also the relevant parts of my config.yml, although I think this matters much.

```
i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

collections:
  - name: 'pages'
    folder: 'src/content/pages'
    create: true
    i18n: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', i18n: true }
      - { name: 'description', label: 'Description', widget: 'text', i18n: true, required: false }
```

**Applicable Versions:**
"gatsby-plugin-netlify-cms": "^4.4.0"
https://unpkg.com/netlify-cms@2.10.76/dist/netlify-cms.js
Git provider: GIthub
OS: Mac, Catalina 
Browser version Brave
yarn version v1.22.10

Is it possible to use these features together? 
Am I using them correctly? 
Or would there be any alternatives for automatically translating original CMS content using an external API?
