### ISSUE TITLE
Option min/max not working for lists

### ISSUE THREAD

**Issue by koxanybak** [decaporg/decap-cms#4733]
**Describe the bug**
min/max not working for lists

**To Reproduce**
Apply the configuration below or just a configuration with the the collection I described.

**Expected behavior**
Publishing should not be allowed if the list has more or less objects than the min/max.

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-app 2.12.19, netlify-cms-core 2.30.3
 - Git provider: GitLab
 - OS: Ubuntu 20.04
 - Browser version: Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**CMS configuration**
```
backend:
  name: gitlab
  repo: webtmk/tite-website
  branch: publications
  auth_type: implicit
  app_id: not_telling_you
  api_root: https://git.tite.fi/api/v4
  base_url: https://git.tite.fi
  auth_endpoint: oauth/authorize

media_folder: static/assets
public_folder: /assets

extension: md

collections:
  - name: tests
    label: Tests
    folder: _content/tests
    create: true
    slug: "{{slug}}"
    fields:
      - name: bugs
        label: Bugs
        widget: list
        types:
          - label: 'a'
            name: 'a'
            widget: 'object'
            fields:
              - {label: a, name: a, widget: string, }

          - label: 'b'
            name: 'b'
            widget: 'object'
            fields:
              - {label: b, name: b, widget: string }

          - label: 'c'
            name: 'c'
            widget: 'object'
            fields:
              - {label: c, name: c, widget: string }
              - label: Options (FI)
                name: options_fi
                widget: list
                min: 2
                field: { label: Option, name: option, widget: string }
                summary: "{{fields.option}}"

        summary: '{{fields.a}}'
        min: 1
        max: 2
```
**Additional context**
Not sure if the problem is only applicabble to this specific configuration or if it applies to lists in general.
