### ISSUE TITLE
Issue with loading draft blog entries - Jekyll

### ISSUE THREAD

**Issue by timmehhh7** [decaporg/decap-cms#4777]
**Describe the bug**
Creating a new post/blog with a Jekyll site works and a draft is created.  However reviewing that same post later via the `workflow` tab, produces some odd results and the card does not load all fields properly.

**To Reproduce**
1. Create a new post and save
2. Leave the page or have another user login and open up the card sitting in drafts from above

**Expected behavior**
The card should load correctly and all content present in the appropriate fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/19749398/103235230-89ca3680-490f-11eb-8c62-0e475af09313.png)
![image](https://user-images.githubusercontent.com/19749398/103235258-9e0e3380-490f-11eb-874c-c259569ac615.png)

**Applicable Versions:**
 - Netlify CMS version: netlify-cms-app 2.14.8, netlify-cms-core 2.36.7, netlify-cms 2.10.78
 - Git provider: GitHub
 - OS: Linux
 - Jekyll: 4
 - Browser version: Version 87.0.4280.109

**CMS configuration**
```
backend:
  name: github
  repo: ArctiqTeam/a-website
  branch: main
publish_mode: editorial_workflow
media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: arctiq
    api_key: <redacted>
collections:
  - name: 'our-blog'
    label: 'Blog'
    folder: '_posts/'
    sort: 'date:asc'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'our-blog/{{slug}}'
    preview_path_date_field: date
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: "YYYY-MM-DD", required: true }
      - { label: 'Banner Image', name: 'image', widget: 'string', required: true }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: true }
      - { label: 'Tags', name: 'tags', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
```

**Additional context**
Note that in the above config I am using `string` for the image field as the `output_filename_only` option is currently broken with Cloudinary ... https://github.com/netlify/netlify-cms/issues/1934
