### ISSUE TITLE
Azure backend branch in config.yml 

### ISSUE THREAD

**Issue by majki600rr** [decaporg/decap-cms#4958]
**Describe the bug**
Specific branch in config.yml  makes nothing when azure backend is used.

**Expected behavior**
All commits update specific branch

**Applicable Versions:**
 - Netlify CMS version: 2.14.22
 - Git provider: Azure
 - OS: Windows 10
 - Browser version chrome 88.0.4324.150

**CMS configuration**
```yml
backend:
  name: azure
  repo: organization/repo
  branch: dev
  tenant_id: XXXXXXX
  app_id: YYYYYYY
```
**Additional context**
I would like to publish whole content to specific (e.g. dev) branch. Is it even possible? Are commits are available only to master branch? There is not much informations about using Azure with netlify cms.
