### ISSUE TITLE
`logo_url` appears not to be used when `local_backend:true`

### ISSUE THREAD

**Issue by paulmsmith** [decaporg/decap-cms#5752]
**Describe the bug**
The login screen when config option `local_backend: true` does not load the custom logo which is set using `logo_url` option. It still shows the NetlifyCMS logo. **however** It does show the custom logo when `local_backend: false`

**To Reproduce**
Update the `config.yml` file for your NelifyCMS instance to have a custom logo and be set to local_backend true:

**Expected behavior**
Logo to change to use custom logo on the login screen. 

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: Github
 - OS: MacOS 11.5.1
 - Browser version [e.g. chrome 22, safari 11] - Version 92.0.4515.159 (Official Build) (x86_64)
 - Node.JS version: 15

**CMS configuration**
```
# Docs: https://www.netlifycms.org/docs/configuration-options/
backend:
  name: github
  branch: main
  repo: user-name/content-site # cms repo
  base_url: https://servicename.herokuapp.com # OAuth server
# when true will assume netlify-cms-proxy-server running: npx netlify-cms-proxy-server
local_backend: true
logo_url: /assets/images/logo.svg
publish_mode: editorial_workflow
public_folder: /assets/images
media_folder: assets/images/uploads
display_url: https://site-url.com/
site_url: https://site-url.com/
collections:
  - name: "guidance"
    label: "Guidance pages"
    label_singular: "Guidance page"
    folder: "app/content/guidance"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
editor:
    preview: true
```

Perhaps a notable difference from the average user is that we're using an external OAuth Client written in Node because we had to use Heroku.
