### ISSUE TITLE
Creating a custom editor widget that is matched by a built in editor widget's regex causes the built in widget to render in place of the custom widget when the article is re-opened.

### ISSUE THREAD

**Issue by edazpotato** [decaporg/decap-cms#5765]
**Describe the bug**
When using a single custom markdown editor component that has the same regex as a built-in editor widget, the custom widget renders, but when the page is reloaded or the article is opened from the dashboard, it renders the default widget.

**To Reproduce**
1. Create a collection with a markdown editor component, that has a custom widget. E.g.
```json
collections:
    - name: "article"
      label: "Articles"
      folder: "content/articles"
      create: true
      slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
      editor:
          preview: false
      fields:
          - label: "Layout"
            name: "layout"
            widget: "hidden"
            default: "articles"
          - label: "Body"
            name: "body"
            widget: "markdown"
            required: false
            editor_components: ["improved-image"]
```
2. Register a custom markdown editor component that, when converted to a block, is matched by a default component's RegEx.
Example matched by the default image component:
```js
CMS.registerEditorComponent({
  id: "improved-image",
  label: "Image",
  fields: [
    {
      name: "src",
      label: "Image",
      widget: "image",
      allow_multiple: false,
      choose_url: false,
    },
    {
      name: "alt",
      label: "Image description",
      widget: "string",
    },
  ],
  pattern: /^\!\[(.+)\]\((.+) "(.+)"\)$/m,
  fromBlock: function (match) {
    return { src: match[0], alt: match[1], };
  },
  toBlock: function (data) {
    return `![${data.alt}](${data.src} "${data.alt}")`;
  },
  toPreview: function (data) {
    return `<img src="${data.src}" alt="${data.alt}" title="${data.alt}"/>`;
  },
});
```
3. Insert a copy of the custom widget into the markdown editor with the plus button
4. Publish the article
5. Leave the article editor then re-open the same article
6. Observe that the custom widget is instead rendering as the built-in widget
**Expected behaviour**
The editor should only test a built-in component's ReEx if it is available to be inserted using the UI.

**Screenshots**

Before re-opening the article:
![image](https://user-images.githubusercontent.com/46797041/131288198-7d0a3abc-81c3-4328-a066-6996849a5110.png)

After saving and re-opening the article:
![image](https://user-images.githubusercontent.com/46797041/131288325-e756a89a-ed26-4b8b-a8fc-dabf002d21e6.png)

**Applicable Versions:**

 - Netlify CMS version: netlify-cms-app 2.15.39 netlify-cms-core 2.47.2 netlify-cms 2.10.159
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Edge 92.0.902.84

**CMS configuration**
```yaml
backend:
    name: git-gateway
    repo: edazpotato/repo-name
    branch: main

media_folder: /public/img
public_folder: /img
collections:
    - name: "article"
      label: "Articles"
      folder: "content/articles"
      create: true
      slug: "{{slug}}-{{day}}-{{month}}-{{year}}"
      editor:
          preview: false
      fields:
          - label: "Layout"
            name: "layout"
            widget: "hidden"
            default: "articles"

          - label: "Title"
            name: "title"
            widget: "string"

          - label: "Date"
            hint: "This is the date that will be displayed on the post, not the publish date."
            name: "date"
            widget: "datetime"

          - name: "tags"
            label: "Tags"
            widget: "list"
            hint: "A comma separated list of tags for the article."

          - label: "Thumbnail image"
            name: "image"
            widget: "image"
            allow_multiple: false
            choose_url: false

          - label: "Link"
            hint: "If set, clicking on the post will go to this url instead of shoing the post body below."
            name: "url"
            widget: "string"
            required: false
```

**Additional context**
