### ISSUE TITLE
"gatsby-plugin-netlify-cms" threw an error while running the onCreateWebpackConfig lifecycle:  Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by animanoir** [decaporg/decap-cms#5849]
Hi. I'm trying to add this plugin into my existing site. The template is a heavily modified version of this https://github.com/weensykim/gatsby-london-after-midnight . Before adding the plugin everything worked, but now, while attempting `gatsby develop` it shows me this error:

```
ERROR #11321  PLUGIN

"gatsby-plugin-netlify-cms" threw an error while running the onCreateWebpackConfig lifecycle:

Cannot read property 'data' of undefined

  279 |   return new Promise(function (resolve, reject) {
  280 |     if (stage === "develop") {
> 281 |       (0, _webpack.default)(config).watch({}, function () {});
      |                            ^
  282 |       return resolve();
  283 |     }
  284 | 

File: node_modules\gatsby-plugin-netlify-cms\gatsby-node.js:281:28
```

**To Reproduce**
1. Follow this tutorials: https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify-cms/ and https://www.netlifycms.org/docs/add-to-your-site/

**Expected behavior**
To build the site with the Netlify CMS plugin on.

**Applicable Versions:**

 - Netlify CMS version: "netlify-cms-app": "^2.15.44"
 - Git provider: GitHub
 - OS: W10

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

# media_folder: static/img
# public_folder: /img

media_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```
