### ISSUE TITLE
i18n doesn't show up editing field in a different language than default

### ISSUE THREAD

**Issue by andreamoro** [decaporg/decap-cms#6310]
Just trying to use NetlifyCMS for the first time, looking at the doc, and I came up with something that should work, but in fact does not.
All the editing fields are proposed for the default language, but not for the secondary one which appears empty.
Not sure if it's me doing something wrong, very likely.

Below an excerpt of my config file

```
i18n:
   structure: single_file
   locales: [en, it]
   default_locale: en

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
  
collections:
  - name: 'blog'
    i18n: true
    label: 'Blog'
    folder: '_posts/'
    create: true
    extension: markdown
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: "blog/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Category', name: 'category', widget: 'select', options: ["Digital Marketing", "SEO", "Ubuntu & *Nix", "Tips", "SEM", "Analytics"] }
      - { label: 'Tags', name: 'tags', widget: 'string', required: false }`
      - ......

```
