### ISSUE TITLE
Roles don't work with self-hosted GoTrue and Git-Gateway

### ISSUE THREAD

**Issue by hrueger** [decaporg/decap-cms#6370]
**Describe the bug**
I'm using netlify-cms together with a selfhosted got-gateway and gotrue. GoTrue is connected to Keycloak via SAML for authentication.
See below for my docker-compose config.

The services are routed to `/.netlify/identity` and `/.netlify/git`. Everything works well, I can sign up, create and edit posts, but it only works without the `GITGATEWAY_ROLES: "editor"` line. If I enable that, I get  `You don't have sufficient permissions to access Netlify CMS`.

The role in the GoTrue database users table is set to `editor`. It also does not work with `admin,editor`.

**To Reproduce**
Setup GoTrue, GitGateway and something for SAML Authentication and use the provided configuration.

**Expected behavior**
I can login successfully.

**Screenshots**

**Applicable Versions:**

 - Netlify CMS version:  2.15.70
 - Git provider: git-gateway
 - OS: Windows 10
 - Browser version Firefox 98

 - Node.JS version:

**CMS configuration**

```yml
backend:
  name: git-gateway
  base_url: https://docs-cms.glue.makepro-x.com
  identity_url: "https://docs-cms.glue.makepro-x.com/.netlify/identity"
  gateway_url:  "https://docs-cms.glue.makepro-x.com/.netlify/git"
  repo: makeproaudio/glue-docs
  branch: main

publish_mode: editorial_workflow
media_folder: docs/static/img/uploads
public_folder: /img/uploads
show_preview_links: false

collections:
  - name: feature
    label: Features
    label_singular: Feature
    folder: docs/usage/features
    identifier_field: title
    description: Features Description...
    extension: md
    widget: "list"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
```

**Additional context**
This is my docker-compose configuration:
```yaml
version: '3.7'
services:
  gotrue:
    image: hrueger/gotrue:1.0.1
    restart: unless-stopped
    environment:
      GOTRUE_JWT_SECRET: ${DOCS_CMS_JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_AUD: localhost
      GOTRUE_DB_DRIVER: mariadb
      GOTRUE_JWT_DEFAULT_GROUP_NAME: editor
      DATABASE_URL: ${GOTRUE_DB_URL}
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 8080
      GOTRUE_SITE_URL: https://docs-cms.glue.makepro-x.com/
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: ${GOTRUE_OPERATOR_TOKEN}
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_EXTERNAL_SAML_ENABLED: "true"
      GOTRUE_EXTERNAL_SAML_METADATA_URL: https://login.makepro-x.com/auth/realms/MPXCloud/protocol/saml/descriptor
      GOTRUE_EXTERNAL_SAML_API_BASE: https://docs-cms.glue.makepro-x.com/.netlify/identity/
      GOTRUE_EXTERNAL_SAML_NAME: MakePro X Login
      GOTRUE_EXTERNAL_SAML_SIGNING_CERT: ''
      GOTRUE_EXTERNAL_SAML_SIGNING_KEY: ''
      GOTRUE_EXTERNAL_LABELS: "{SAML: MakePro X Login}"


  git-gateway:
    image: hrueger/git-gateway:1.0.0
    restart: unless-stopped
    environment:
      GITGATEWAY_JWT_SECRET: ${DOCS_CMS_JWT_SECRET}
      GITGATEWAY_DB_DRIVER: mysql
      DATABASE_URL: ${GITGATEWAY_DB_URL}
      GITGATEWAY_API_HOST: 0.0.0.0
      PORT: 8080
      GITGATEWAY_GITHUB_ACCESS_TOKEN: ${GITGATEWAY_GITHUB_ACCESS_TOKEN}
      GITGATEWAY_GITHUB_REPO: "makeproaudio/glue-docs"
      GITGATEWAY_GITHUB_BRANCH: main
      # GITGATEWAY_ROLES: "editor"
```
