### ISSUE TITLE
Extra characters getting added to body of md files (ZERO WIDTH NO-BREAK SPACE)

### ISSUE THREAD

**Issue by snacksthecat** [decaporg/decap-cms#6602]
**Describe the bug**
An extra character (ZERO WIDTH NO-BREAK SPACE) is being added to body of the produced md files when creating a collection entry through the CMS.

**To Reproduce**
1) I defined my admin.yml.
2) Created a new entry through the CMS and published. Netlify built site.
3) Fetch/pull the updates from GitHub.
4) Opened the md file in VS Code and saw that each line had an extra character inserted.

**Expected behavior**
Expected to see only the contents that were typed into the CMS, without the extra character.

**Screenshots**
![chrome_Xrrz4UtL6p](https://user-images.githubusercontent.com/26846031/203450140-af45a7d9-56fa-4a9e-89f7-0532c5258c78.png)

![Code_UiBoYU1kNV](https://user-images.githubusercontent.com/26846031/203450302-dec70f78-b6c2-401b-8c67-e0f5adb7b13e.png)

**Applicable Versions:**
 - Netlify CMS app version: netlify-cms-app 2.15.72
 - Netlify CMS core version: netlify-cms-core 2.55.2
 - Netlify CMS version: netlify-cms 2.10.192
 - Git provider: GitHub
 - OS: Windows 10
 - Browser version: Chrome 107.0.5304.107
 - Text editor version: Visual Studio Code 1.73.1
 - Hugo version: v0.105.0-0e3b42b4a9bdeb4d866210819fc6ddcf51582ffa+extended

**CMS configuration**
```
backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    extension: md
    format: toml-frontmatter
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Categories", name: "categories", widget: "relation", collection: "categories", value_field: "title", display_fields: ["title"], search_fields: ["title"], multiple: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    extension: md
    format: toml-frontmatter
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
```
