### ISSUE TITLE
Wrong text overflow in french localization

### ISSUE THREAD

**Issue by shiipou** [decaporg/decap-cms#6605]
**Describe the bug**

In the french localization, some elements won't render in the correct size. Which make is hard to read.

![image](https://user-images.githubusercontent.com/38187238/203726222-07cd5364-7dc8-459b-b201-cfeb3e780aae.png)

**To Reproduce**

**Expected behavior**

We must be able to read all the text like this : 
![image](https://user-images.githubusercontent.com/38187238/203731737-219e7c9f-b144-405b-a452-03577cb7db61.png)

**Applicable Versions:**

 - Netlify CMS version: https://unpkg.com/netlify-cms@^2.0.0/dist/netlify-cms.js
 - Git provider: GitLab
 - OS: Windows 10
 - Browser version 102.3.0esr

**CMS configuration**

```yaml
backend:
  name: gitlab
  repo: cms/netlify-commun # Path to your GitLab repository
  branch: main
  auth_type: pkce # Required for pkce
  app_id: xxxx
  api_root: https://gitlab.xxxx.net/api/v4
  base_url: https://gitlab.xxxx.net/
  auth_endpoint: oauth/authorize
locale: fr
media_folder: public/img
public_folder: img
collections:
  - name: "page"
    label: "Pages"
    folder: "content/pages/"
    format: "frontmatter"
    create: true
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime"}
      - { label: "Body", name: "body", widget: "markdown", required: false}
```

**Additional context**
