### ISSUE TITLE
"required: false" is not working for objects(images), lists, is there any solution?

### ISSUE THREAD

**Issue by masliakova1** [decaporg/decap-cms#6620]
Hi, I work with Netlify CMS + eleventy.

**Describe the bug**
I added a page to the CMS, it contains lists, object like images, I used required, so if we don;'t need images, or other part of the list, then we have an option not to add it. I can't share the whole project here, as it's private. I will attach a screenshot.

**To Reproduce**

**Expected behavior**
With "required:false" I was expecting object and lists not to be required to add. 

**Screenshots*
![Screenshot2022_12_08_112247](https://user-images.githubusercontent.com/88039317/206435700-6b17224f-2035-43d3-a628-c4321d265557.jpg)
*
![Screenshot2022_12_08_112426](https://user-images.githubusercontent.com/88039317/206435729-08571c92-17f1-479c-b36c-adaff70a9dcb.jpg)
![Screenshot2022_12_08_112744](https://user-images.githubusercontent.com/88039317/206435745-8739198f-a3f3-4364-83f8-4687de4f9bea.jpg)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version: 16.14.0

**CMS configuration**
```yaml
backend:
  name: github
  repo: ----
  branch: main
  base_url: ---
  auth_endpoint: api/auth
  preview_context: Vercel
publish_mode: editorial_workflow
media_folder: "/images"
public_folder: "/images"
collections:
  - name: market-analysis
    label: Market-analysis
    create: true
    folder: "src/market-analysis"
    slug: "{{slug}}"
    fields:
      - label: Layout
        name: layout
        default: /layouts/topic2c.pug
        widget: hidden
        required: false
      - label: Name
        name: title
        widget: string
        required: false
      - label: MainTopic1
        name: mainTopic
        widget: string
        required: false
      - label: Topic1
        name: topic1
        widget: string
        required: false
      - label: Topic Description
        name: topicDesc
        widget: string
        required: false
      - label: Pictures
        name: picture
        widget: object
        required: false
        fields:
          - {
              name: "name",
              label: "Picture 6 name",
              widget: "string",
              hint: "write imageName but with 1st capital",
              required: false,
            }
          - {
              name: "file",
              label: "File 6",
              media_folder: "/images/",
              widget: "image",
              required: false,
            }
          - {
              name: "imageName",
              label: "Image Name 6",
              widget: "string",
              hint: "the name of the picture you are uploading ex example.png so write exmaple",
              required: false,
            }
      - name: reportPointText
        label: Report Points Header
        widget: string
        required: false
      - name: points
        label: Point 1
        widget: list
        required: false
        fields:
          - name: point
            label: Point
            widget: string
            required: false
          - name: pointdesc
            label: Point Desc
            widget: string
            required: false
          - name: imageName
            label: SVG Image name
            widget: string
            hint: You have 8 to choose from, just type one in-> icon-graph, icon-market, icon-pandemic, icon-price, icon-size, icon-time, icon-usage, icon-users.
            required: false
```
