### ISSUE TITLE
Support multiple images with the default media picker

### ISSUE THREAD

**Issue by TheEnbyWitch** [decaporg/decap-cms#6730]
**Is your feature request related to a problem? Please describe.**
The default media picker does not allow selection of multiple images, despite the image field supporting that as a feature
```
- label: "Zdjęcia"
  name: photos
  widget: image
  media_library:
    config:
      multiple: true
```

**Describe the solution you'd like**
If possible, I would like there to be a checkbox on every image that I could tick, kinda like there is one in the WordPress image picker

**Describe alternatives you've considered**
I have considered Cloudinary and Uploadcare, but I don't want to depend on another service for this kind of stuff on this project.
