### ISSUE TITLE
Image widgets added inside a markdown widget field are not shown in preview

### ISSUE THREAD

**Issue by thecodemine** [decaporg/decap-cms#6785]
## Describe the bug

No preview shown when adding an image in the markdown editor  

## To Reproduce

Steps to reproduce the behavior. For example:
1. Go to 'markdown editor' (markdown widget)
2. Click on 'add component' button
3. Select 'Image'
4. Choose an image to insert
5. Add title and alt text for the image
6. Note that no preview of the image is shown

## Expected behavior

images (image widgets) added inline should be shown in the preview 

## Screenshots

![image](https://github.com/decaporg/decap-cms/assets/128751492/e63e3345-3337-45c3-9abc-0a78707dcbaa)

## Applicable Versions:

 - Netlify CMS version: 2.10.192
 - Git provider: GitHub
 - OS: Pop!_OS 22.04 LTS
 - Browser version: Version 112.0.5615.165 (Official Build) (64-bit)
 - Node.JS version: v16.13.0

## CMS configuration
<details>
<summary>config.yml</summary>

```
locale: 'sv'
publish_mode: editorial_workflow
display_url: https://redacted.com
backend:
  name: github
  repo: redacted/redacted.com
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://redacted.com
  auth_endpoint: /api/auth
media_folder: src/images
public_folder: /images
collections:
  - name: 'config'
    label: 'konfiguration'
    files: 
      - name: 'contact_form'
        label: 'Kontakt formulär'
        file: 'src/_data/contact_form.json'
        widget: "object"
        fields: 
          - name: sv
            widget: list 
            fields: 
              - { name: subject, widget: string }
              - { name: email, widget: string }
          - name: en
            widget: list 
            fields: 
              - { name: subject, widget: string }
              - { name: email, widget: string }
          - name: default
            widget: list 
            fields: 
              - { name: subject, widget: string }
              - { name: email, widget: string } 
            
  - name: 'blog-swedish' 
    label: 'Blogginlägg (svenska)'
    folder: 'src/pages/_cms_content'
    create: true
    filter: {field: "language", value: "sv"}
    summary: '{{day}}/{{month}}/{{year}} {{hour}}:{{minute}} | {{title}}' # optional summary for a tree node, defaults to the inferred title field
    view_groups:
      - label: År
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
    view_filters:
      - label: Utkast
        field: draft
        pattern: true
    slug: '{{slug}}'
    editor:
      preview: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'sv' }
      - { label: 'Datum', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ",  hint: 'Datum som visar när inlägget gjordes. Om datumet och tiden är i framtiden
    kommer inlägget att släppas ut på siten först vid den tiden.' }
      - { label: 'Utkast', name: 'draft', widget: 'boolean', default: true, hint: 'Inlägget kommer inte att visas på sidan även fast det är publicerat.' }
      - { label: 'Visa i flödet', name: 'show_in_flow', widget: 'boolean', default: true, hint: 'Inlägget visas i flödet på hemsidan.' }
      - { label: 'Visa som prioriterat tills', name: 'sticky_until', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ", hint: 'Inlägget visas högst upp i flödet på hemsidan tills denna tidpunkt.' }
      - { label: "Huvudbild", name: "image", widget: "image", required: false, choose_url: true, allow_multiple: false, hint: 'Bild som visas högst upp i inlägget och då det visas i flödet på hemsidan. Använd t.ex. **[Squoosh.app](http://squoosh.app)** för att se till att bilden är lagom stor innan du laddar upp den.' }
      - { label: 'Titel', name: 'title', widget: 'string', hint: 'Sidans titel som visas i inläggets intro och då det visas i flödet på sidan.' }
      - { label: 'Beskrivning', name: 'short_description', widget: 'string', required: false, hint: 'Kort beskrivning av inlägget då det visas i flödet på sidan.' }
      - { label: 'Sidinnehåll', name: 'body', widget: 'markdown', sanitize_preview: true, hint: 'Sidans innehåll, Se t.ex. **[markdown cheat-sheet](/markdown-cheat-sheet)** för exempel.' }
      - { label: "Taggar", name: "tags", widget: "list", required: false, hint: 'taggar som beskriver innehållet' }
    meta: { path: { widget: string, label: 'Path', index_file: 'index',  default: "/{{year}/{{month}}/{{}}"} }

  - name: 'blog-english' 
    label: 'Blogginlägg (engelska)'
    folder: 'src/pages/_cms_content/en'
    create: true
    filter: {field: "language", value: "en"}
    summary: '{{day}}/{{month}}/{{year}} {{hour}}:{{minute}} | {{title}}' # optional summary for a tree node, defaults to the inferred title field
    view_groups:
      - label: År
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
    view_filters:
      - label: Utkast
        field: draft
        pattern: true
    slug: '{{slug}}'
    editor:
      preview: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'en' }
      - { label: 'Datum', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ",  hint: 'Datum som visar när inlägget gjordes. Om datumet och tiden är i framtiden
    kommer inlägget att släppas ut på siten först vid den tiden.' }
      - { label: 'Utkast', name: 'draft', widget: 'boolean', default: true, hint: 'Inlägget kommer inte att visas på sidan även fast det är publicerat.' }
      - { label: 'Visa i flödet', name: 'show_in_flow', widget: 'boolean', default: true, hint: 'Inlägget visas i flödet på hemsidan.' }
      - { label: 'Visa som prioriterat tills', name: 'sticky_until', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ", hint: 'Inlägget visas högst upp i flödet på hemsidan tills denna tidpunkt.' }
      - { label: "Huvudbild", name: "image", widget: "image", required: false, choose_url: true, allow_multiple: false, hint: 'Bild som visas högst upp i inlägget och då det visas i flödet på hemsidan. Använd t.ex. **[Squoosh.app](http://squoosh.app)** för att se till att bilden är lagom stor innan du laddar upp den.' }
      - { label: 'Titel', name: 'title', widget: 'string', hint: 'Sidans titel som visas i inläggets intro och då det visas i flödet på sidan.' }
      - { label: 'Beskrivning', name: 'short_description', widget: 'string', required: false, hint: 'Kort beskrivning av inlägget då det visas i flödet på sidan.' }
      - { label: 'Sidinnehåll', name: 'body', widget: 'markdown', sanitize_preview: true, hint: 'Sidans innehåll, Se t.ex. **[markdown cheat-sheet](/markdown-cheat-sheet)** för exempel.' }
      - { label: "Taggar", name: "tags", widget: "list", required: false, hint: 'taggar som beskriver innehållet' }

  - name: 'blog-german' 
    label: 'Blogginlägg (tyska)'
    folder: 'src/pages/_cms_content/de'
    create: true
    filter: {field: "language", value: "de"}
    summary: '{{day}}/{{month}}/{{year}} {{hour}}:{{minute}} | {{title}}' # optional summary for a tree node, defaults to the inferred title field
    view_groups:
      - label: År
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
    view_filters:
      - label: Utkast
        field: draft
        pattern: true
    slug: '{{slug}}'
    editor:
      preview: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'de' }
      - { label: 'Datum', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ",  hint: 'Datum som visar när inlägget gjordes. Om datumet och tiden är i framtiden
    kommer inlägget att släppas ut på siten först vid den tiden.' }
      - { label: 'Utkast', name: 'draft', widget: 'boolean', default: true, hint: 'Inlägget kommer inte att visas på sidan även fast det är publicerat.' }
      - { label: 'Visa i flödet', name: 'show_in_flow', widget: 'boolean', default: true, hint: 'Inlägget visas i flödet på hemsidan.' }
      - { label: 'Visa som prioriterat tills', name: 'sticky_until', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ", hint: 'Inlägget visas högst upp i flödet på hemsidan tills denna tidpunkt.' }
      - { label: "Huvudbild", name: "image", widget: "image", required: false, choose_url: true, allow_multiple: false, hint: 'Bild som visas högst upp i inlägget och då det visas i flödet på hemsidan. Använd t.ex. **[Squoosh.app](http://squoosh.app)** för att se till att bilden är lagom stor innan du laddar upp den.' }
      - { label: 'Titel', name: 'title', widget: 'string', hint: 'Sidans titel som visas i inläggets intro och då det visas i flödet på sidan.' }
      - { label: 'Beskrivning', name: 'short_description', widget: 'string', required: false, hint: 'Kort beskrivning av inlägget då det visas i flödet på sidan.' }
      - { label: 'Sidinnehåll', name: 'body', widget: 'markdown', sanitize_preview: true, hint: 'Sidans innehåll, Se t.ex. **[markdown cheat-sheet](/markdown-cheat-sheet)** för exempel.' }
      - { label: "Taggar", name: "tags", widget: "list", required: false, hint: 'taggar som beskriver innehållet' }

  - name: 'blog-finnish' 
    label: 'Blogginlägg (finska)'
    folder: 'src/pages/_cms_content/fi'
    create: true
    filter: {field: "language", value: "fi"}
    summary: '{{day}}/{{month}}/{{year}} {{hour}}:{{minute}} | {{title}}' # optional summary for a tree node, defaults to the inferred title field
    view_groups:
      - label: År
        field: date
        # groups items based on the value matched by the pattern
        pattern: \d{4}
    view_filters:
      - label: Utkast
        field: draft
        pattern: true
    slug: '{{slug}}'
    editor:
      preview: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'fi' }
      - { label: 'Datum', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ",  hint: 'Datum som visar när inlägget gjordes. Om datumet och tiden är i framtiden
    kommer inlägget att släppas ut på siten först vid den tiden.' }
      - { label: 'Utkast', name: 'draft', widget: 'boolean', default: true, hint: 'Inlägget kommer inte att visas på sidan även fast det är publicerat.' }
      - { label: 'Visa i flödet', name: 'show_in_flow', widget: 'boolean', default: true, hint: 'Inlägget visas i flödet på hemsidan.' }
      - { label: 'Visa som prioriterat tills', name: 'sticky_until', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mmZ", hint: 'Inlägget visas högst upp i flödet på hemsidan tills denna tidpunkt.' }
      - { label: "Huvudbild", name: "image", widget: "image", required: false, choose_url: true, allow_multiple: false, hint: 'Bild som visas högst upp i inlägget och då det visas i flödet på hemsidan. Använd t.ex. **[Squoosh.app](http://squoosh.app)** för att se till att bilden är lagom stor innan du laddar upp den.' }
      - { label: 'Titel', name: 'title', widget: 'string', hint: 'Sidans titel som visas i inläggets intro och då det visas i flödet på sidan.' }
      - { label: 'Beskrivning', name: 'short_description', widget: 'string', required: false, hint: 'Kort beskrivning av inlägget då det visas i flödet på sidan.' }
      - { label: 'Sidinnehåll', name: 'body', widget: 'markdown', sanitize_preview: true, hint: 'Sidans innehåll, Se t.ex. **[markdown cheat-sheet](/markdown-cheat-sheet)** för exempel.' }
      - { label: "Taggar", name: "tags", widget: "list", required: false, hint: 'taggar som beskriver innehållet' }

```

</details>

## Additional context

By modifying the markdown manually, after adding the image widget, you can force the image to show up in the preview (of course the image widget will no longer be shown in the rich text view)

### before
```
There is no character before or after the image - and no image is in the preview

![alt text](/images/testing.jpg "testing")
``` 

### after
```
There is a whitespace before the image (could be any character) -and image is shown in preview

 ![alt text](/images/testing.jpg "testing")
```
