### ISSUE TITLE
Custom Logo not loading

### ISSUE THREAD

**Issue by pxrpl** [decaporg/decap-cms#6786]
I added a custom panel logo, and it does not replace the netlify cms one. Please help me, heres my code

```
backend:
  name: git-gateway
  branch: main 
  logo_url: /images/banner.svg

media_folder: "src/images/posts"
public_folder: "/images/posts"

editor:
  preview: true

stylesheets:
  - /src/css/main.css
  - /src/css/syntax.css

collections:
  
     - name: "blog"
       label: "Blog"
       folder: "src/posts"
       create: true
       slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
       fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "date" }
          - { label: "Preview Image", name: "previewImage", widget: "image", value_type: "string", default: "", media_library: { config: { fileMeta: [{ media_folder: "src/images/posts", public_folder: "/images/posts" }], allow_multiple: false }, enabled: true }, hint: "Enter the path to the preview image. Make sure to remove 'src/' from the path.", required: false, value_template: '{{ "/images/posts/" | concat: value | replace: "src/", "" | url_encode }}' }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Post URL", name: "postUrl", widget: "string", default: "{{ page.url | url }}" }
          - { label: "Body", name: "body", widget: "markdown" }

theme:
  mode: dark
```

heres the repo. [repo](https://github.com/pxrpl/blog)
