### ISSUE TITLE
Allowing auto-generated fields

### ISSUE THREAD

**Issue by pumguy** [decaporg/decap-cms#6819]
Adding a non-editable widget for auto-generated contents which can reference contents from other fields
Such as
```yaml
collections:
  - name: person
    fields:
      - { name: "first_name", widget: "string" }
      - { name: "last_name", widget: "string" }
      - { name: "full_name", widget: "auto-genterated", default: "{{ fields.first_name }} {{ fields.last_name }}" }
```
makes the "full_name" field auto-generated from the other two fields in the same post during editing.
