### ISSUE TITLE
Error loading config.yml

### ISSUE THREAD

**Issue by hellopeplum** [decaporg/decap-cms#6828]
I am building a pretty simple Nuxt3 static site, with decap CMS

here's my config

```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# media_folder: public/img
# public_folder: /img
site_url: https://peplum.netlify.app/

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

on /admin I get the error that config.yml failed to load, please check. Unable to fix it, any help is greatly appreciated.

Best
