### ISSUE TITLE
The list widget on my site is not working properly

### ISSUE THREAD

**Issue by Albertyhu** [decaporg/decap-cms#6864]
I am integrating Netlify CMS into my Astro site.
I created two list widgets.
One allows the bloggers to upload images.
The other one allows the bloggers to write down tags associated with the blog.

**Describe the bug**
When the admin site renders the form, the inputs for images and tags are not working properly.
Any existing images or tags will render as “No undefined”.
![image](https://github.com/decaporg/decap-cms/assets/13213934/5661c409-fadc-4a00-974b-7e7b79f8da6f)

The image input renders as a text input. It doesn’t allow the user to paste an image URL or upload an image from his device.

Both the image input and tag input only allows the user to write only one character for some reason and not more.

Also, when a letter is typed into the tag input, the following error appears: 
```
ListControl.js:163 Uncaught TypeError: t.getObjectValue(...).set is not a function
```

**To Reproduce**
1. Create an Astro project. 
2. Create an admin folder in the public directory
3. Create a file called index.astro 
4. Copy and paste the following code onto index.html
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>

  <!-- Include the styles for the Netlify CMS UI, after your own styles -->
  <link rel="stylesheet" href="https://unpkg.com/netlify-cms@^1.0.0/dist/cms.css" />
  <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
</head>
<body>
  <!-- Include the script that builds the page and powers Netlify CMS -->
  <script src="https://unpkg.com/netlify-cms@^1.0.0/dist/cms.js"></script>
</body>
</html>
```
5. Create a file called config.yml and copy and paste the following code into it
```
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: src/assets
public_folder: /assets
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/pages/posts"
    create: "true"
    delete: "true"
    fields:
      - name: "layout"
        widget: "hidden"
        label: "Layout"
        default: "../../layouts/MarkdownPostLayout.astro"
      - name: "title"
        widget: "string"
        label: "Title"
      - name: "pubDate"
        widget: "datetime"
        label: "Published date"
      - name: "description"
        widget: "string"
        label: "Description"
      - name: "author"
        widget: "string"
        label: "Author"
      - name: "images"
        widget: "list"
        label: "Images"
        field: [{name: "image", widget: "image", label: "Image"}]
      - name: "tags"
        widget: "list"
        label: "Tags"
        field: [{name: "tag", widget: "string", label: "Tag"}]
      - name: "body"
        widget: "markdown"
        label: "Body"
```

6. Create an index.astro file in pages directory with a default HTML template
7. Copy and paste the following code into the header of index.astro
```
        <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
```
8. Copy and paste the following code right before the closing body tag of index.astro
```
        <script>
            if (window.netlifyIdentity) {
                window.netlifyIdentity.on("init", user => {
                    if (!user) {
                        window.netlifyIdentity.on("login", () => {
                        document.location.href = "/admin/";
                    });
                    }
                });
            }
        </script>
``` 

**Expected behavior**
When a user tries to create a new blog, he should be able to add a new image by uploading an image from his device or pasting a image url. The user should also be allowed to type names for tags being added to the blog. 

**Screenshots**
![image](https://github.com/decaporg/decap-cms/assets/13213934/cd2ac6cf-064d-4a06-bb8a-0772608a1140)

**Applicable Versions:**

 - Netlify CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version: v18.13.0

**CMS configuration**

    NetlifyCMS({
    config: {
      backend: {
        name: 'git-gateway',
        branch: 'main',
      },
      publish_mode: "editorial_workflow",
      media_folder: "src/assets",
      public_folder: "/assets/uploads", 
      collections: [{
        name: "posts",
        label: "Blog Posts",
        folder: "src/pages/posts",
        create: true,
        delete: true,
        fields: [{
          name: "layout",
          widget: "hidden",
          label: "Layout",
          default: '../../layouts/MarkdownPostLayout.astro',

        }, {
          name: "title",
          widget: 'string',
          label: "Title"
        }, {
          name: "pubDate",
          widget: 'datetime',
          label: "Published date"
        }, {
          name: "description",
          widget: 'string',
          label: "Description"
        }, {
          name: "author",
          widget: 'string',
          label: "Author"
        }, {
          name: "images",
          widget: 'list',
          label: "Images",
          fields: [{
            name: "image",
            widget: 'image',
            label: "Image"
          }]
        }, {
          name: "tags",
          widget: 'list',
          label: "tags",
          fields:[{
            name: "tag",
            widget: "string",
            label: "Tag",             
          }]
        }, {
          name: "body",
          widget: 'markdown',
          label: "Body"
        },
      ]
      }],
    }
    }), 
**Additional context**
Here is the Github repository for the project: https://github.com/Albertyhu/Astro-Template

**Comment by Albertyhu** [comment]
I was able to get the image input to work properly. The user can now upload images from his device. 
However, the tags input is still not working. Only one letter can be types into the input. 

Here is my updated config.yml file:

```
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: src/assets
public_folder: /assets
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/pages/posts"
    create: "true"
    delete: "true"
    fields:
      - name: "layout"
        widget: "hidden"
        label: "Layout"
        default: "../../layouts/MarkdownPostLayout.astro"
      - name: "title"
        widget: "string"
        label: "Title"
      - name: "pubDate"
        widget: "datetime"
        label: "Published date"
      - name: "description"
        widget: "string"
        label: "Description"
        required: false
      - name: "author"
        widget: "string"
        label: "Author"
      - name: "images"
        widget: "list"
        label: "Images"
        required: false
        field: {label: "Image", name: "image", widget: "image"}
      - name: "tags"
        widget: "list"
        label: "Tags"
        required: false
        field: {label: "Tag", name: "tag", widget: "string"}
      - name: "body"
        widget: "markdown"
        label: "Body"
```

**Comment by Albertyhu** [comment]
Also, there are issues with creating and saving new posts. 

The deploy logs would show the following error:

![image](https://github.com/decaporg/decap-cms/assets/13213934/063affc5-48fe-4f43-a6cd-d8c1e47669b7)

**Comment by Albertyhu** [comment]
I finally figured out that the problem is how my config.yml file was written. 

Widgets that are lists should be written as follows:
```
      - name: "images"
        widget: "list"
        label: "Images"
        required: "false"
        fields: 
          - {label: "Image", name: "url", choose_url: "true", media_folder: "src/assets/uploads", widget: "image"}
          - {label: "Alt text", name: "alt", widget: "string"}
```
