### ISSUE TITLE
Files uploaded through file widget skip Netlify Large Media/git-lfs

### ISSUE THREAD

**Issue by PhilipHow** [decaporg/decap-cms#6866]
**Describe the bug**

Files (possibly when only using filtered file extensions - e.g. `.mp3`) uploaded with the [File](https://decapcms.org/docs/widgets/#file) widget to an `git-lfs track`ed location, are not uploaded to Netlify Large Media/git-lfs.

**To Reproduce**
- Set up Netlify Large Media, link with the Netlify site
- Track uploaded `mp3` files using git-lfs e.g `src\static\uploads\*.mp3`
- Create Collection using the File widget
- Upload mp3 file using the File widget
- File is uploaded as raw to repo, and not to Netlify Large Media

**Expected behavior**

- File is uploaded through git-lfs to Netlify Large Media

**Applicable Versions:**
- netlify-cms-app 2.15.72
- bootstrap.js:85 netlify-cms-core 2.55.2
- index.js:27 netlify-cms 2.10.192

**CMS configuration**
```
backend:
  name: git-gateway
  repo: ...
media_folder: "src/static/uploads"
public_folder: "/uploads"
use_large_media_transforms_in_media_library: false
collections:
  - name: "talk"
    label: "Talk"
    folder: "src/talks" 
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "talk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Record Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Audio File", name: "audio-file", widget: "file"}
```

**Additional context**
- Adding mp3 files locally, committing and pushing correctly uploads via Netlify Large Media
- Pulling after testing triggers this warnings:
- `Encountered 1 file(s) that should have been pointers, but weren't:
        src/static/uploads/blahblah.mp3`
