### ISSUE TITLE
TypeError: process.cwd is not a function

### ISSUE THREAD

**Issue by niekbiesterbos** [decaporg/decap-cms#6903]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.0.6`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: src/public/images/uploads
public_folder: /images/uploads
i18n:
  &a1
  structure: multiple_folders
  locales:
    - nl
    - en
  default_locale: en
collections:
  - name: help
    label: Help
    folder: src/content/help
    summary: "{{title | upper}} - {{date | date('YYYY-MM-DD')}} - {{body |
      truncate(20, '***')}}"
    format: frontmatter
    create: true
    slug: "{{slug}}"
    i18n: *a1
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: translate
      - label: Publish Date
        name: date
        widget: datetime
        i18n: none
      - label: Body
        name: body
        widget: markdown
        i18n: translate
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by martinjagodic** [comment]
Hi @niekbiesterbos, please fill out all the fields in the issue template. The information you provided is not enough to debug the problem.

I'm closing the issue for now. Once you add the missing information, I can open it again.

**Comment by vnourdin** [comment]
I have the same problem, the error shows up when I try to edit a "markdown" field !
I thought it was relative to i18n, but even with a minimalist config, I got it.
If I publish, the markdown field isn't saved.

Here is my minimal config to reproduce :
```yaml
backend:
  name: gitlab
  repo: ###
  auth_type: pkce
  branch: "main"
  app_id: ###
  cms_label_prefix: cms/

media_folder: "/src/img"

collections:
  - label: "content"
    name: "content"

    folder: "src/content"
    format: "json"
   
    create: true

    fields:
      - {label: "title", name: "title", widget: "string"}
      - { label: "content", name: "content", widget: "markdown", modes: ["rich_text"] }
```
Same problem if I don't specify the format and thus using frontmatter.
