### ISSUE TITLE
i18n content with multiple_folders is broken in DecapCMS 3.0.0

### ISSUE THREAD

**Issue by Billybobbonnet** [decaporg/decap-cms#6913]
While it works properly with the versions prior to 3.0.0, it fails to display content after 3.0.0

Here is my `  config.yml`
```
backend:
  name: github
  repo: XXX/seed
  branch: main
  base_url: https://XXXXXXXXi.execute-api.eu-west-2.amazonaws.com/
  auth_endpoint: "/dev/auth"
  cms_label_prefix: "XXX/"
publish_mode: editorial_workflow
media_folder: "public"
public_folder: "/"
site_url: https://XXX.fr
logo_url: /icon.png
show_preview_links: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en
collections:
  - name: "editorial" 
    label: "Editorial content" # Used in the UI
    i18n: true
    slug: "{{id}}"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: 
      - { label: id, name: id, widget: string, i18n: duplicate }
      - { label: Body, name: body, widget: markdown, i18n: true }
```

These are very simple documents. Everything works when I simply change the script to import from 
`https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js` to `https://unpkg.com/netlify-cms@^2.10.17/dist/netlify-cms.js`
