### ISSUE TITLE
Links are showing as markdown

### ISSUE THREAD

**Issue by jdromero88** [decaporg/decap-cms#6916]
Hi! I'm having the next issue. When I add a link in the author's bio. the Link is rendered as md.
for example this is my author md file

```md
---
name: Juan Doe
position: unkown
current_staff: true
---
Bacon ipsum dolor amet alcatra *andouille* pork chop shank swine ham tail frankfurter.  Capicola salami drumstick corned beef.  T-bone **rump** burgdoggen, landjaeger turkey tongue chislic shankle picanha ham hock sausage.  Pork [bresaola](www.decapcms.org) biltong swine buffalo [prosciutto](https://duckduckgo.com).

`Biltong chicken swine short ribs, shank chuck short loin pig hamburger pork belly.  Turkey picanha hamburger tri-tip, ball tip pork pork chop.  Frankfurter ball tip biltong ham hock picanha pancetta strip steak corned beef fatback sirloin beef pork loin chislic boudin.  Frankfurter strip steak prosciutto short loin venison ribeye bacon pork chop chicken.`

Biltong chicken swine short ribs, shank chuck short loin pig hamburger pork belly.  Turkey picanha hamburger tri-tip, ball tip pork pork chop.  Frankfurter ball tip biltong ham hock picanha pancetta strip steak corned beef fatback sirloin beef pork loin [chislic](hello.com) boudin.  Frankfurter strip steak prosciutto short loin venison ribeye bacon pork chop chicken.
```
and it's being rendered like this:
![image](https://github.com/decaporg/decap-cms/assets/51330062/2c0fdbf3-fd31-4d8a-b5f2-11a377f6af21)

Author's collection
```yml
  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    identifier_field: name
    slug: '{{slug}}'
    sortable_fields: ['name', 'position']
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', choose_url: false, required: false }
      - { label: 'Current Staff', name: 'current_staff', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
```

**Applicable Versions:**
 - decap-cms-app 3.0.7
 - decap-cms-core 3.2.4
 - decap-cms 3.0.7
 - Git provider: GitHub
 - OS: Linux Mint 21.2 x86_64
 - Browser version Firefox 117.0.1 (64-bit)

**CMS configuration**
```yml
# config.yml
local_backend: true

# live
backend:
  name: git-gateway
  # branch: main # Branch to update (optional; defaults to master)
  branch: dev # Branch to update. Dev is now selected so we dont override any content that the program is adding.

media_folder: '_uploads'
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads
# publish_mode: 'editorial_workflow'
display_url: 'https://indianstates.csis.org'
logo_url: 'https://raw.githubusercontent.com/CSIS-iLab/energy-database/main/public/android-chrome-192x192.png'
collections:
  - name: 'analysis'
    label: 'Analyses'
    label_singular: 'Analysis'
    folder: '_analysis/'
    create: true
    editor:
      preview: false
    # slug: '{{slug}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields: ['title', 'date', 'author', 'states']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'analysis' }
      - { label: 'Is analysis', name: 'is_analysis', widget: 'hidden', default: true }
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'analysis' }
      # - { label: 'Post Type', name: 'post_type', widget: 'relation', collection: 'post_types',
      #     display_fields: [title],
      #     search_fields: [title],
      #     value_field: 'title'
      #   }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', time_format: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' }}
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'States', name: 'states', widget: 'relation', collection: 'states', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true, display_fields: [title], search_fields: [title], value_field: 'title', required: false  }
      - { label: 'Sub Sectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true, display_fields: [title], search_fields: [title], value_field: 'title', required: false }
      - { label: 'Is Featured?', name: 'is_featured', widget: 'boolean', default: false, required: false }
      - { label: 'Featured Image', name: 'feature_image', widget: 'image', choose_url: false, required: false }
      - { label: 'Featured image credit', name: 'feature_image_credit', widget: 'text', required: false }
      - label: 'Sources'
        label_singular: 'Source'
        name: 'sources'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false  
      - label: 'Details'
        label_singular: 'Detail'
        name: 'details'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false
      - { label: 'Author', name: 'author', widget: 'relation', collection: 'authors', multiple: true, display_fields: [name], search_fields: [name], value_field: 'name', }
      - { label: 'PDF', name: 'pdf', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'articles'
    label: 'Articles'
    label_singular: 'Article'
    folder: '_posts/'
    create: true
    editor:
      preview: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields: ['title', 'date', 'author', 'states']
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'articles' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'articles' }
      - { label: 'Is analysis', name: 'is_analysis', widget: 'hidden', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', time_format: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' }}
      - { label: 'States', name: 'states', widget: 'relation', collection: 'states', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Subsectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - label: 'Sources'
        label_singular: 'Source'
        name: 'sources'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false  
      - label: 'Details'
        label_singular: 'Detail'
        name: 'details'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }

  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    identifier_field: name
    slug: '{{slug}}'
    sortable_fields: ['name', 'position']
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', choose_url: false, required: false }
      - { label: 'Current Staff', name: 'current_staff', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'national-goals'
    label: 'National Goals'
    label_singular: 'National Goal'
    folder: '_national-goals/'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title', 'tags', 'last_updated_at']
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'national-goals' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' }}
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Subsectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
          required: false
        }
      - { label: 'Data source', name: 'data_source', widget: 'hidden',  default: '{{replace-this-with-data-name}}'}
      - { label: 'Data Label', name: 'data_label', widget: 'string', hint: 'The suffix to appear after the data value on the progress bars and the state page (MW, KM, etc.)' }
      - { label: 'Data Missing Message', name: 'data_missing_message', widget: 'string', hint: 'The text that appears before the state name on the state pages in the "related national goals" box if there is no value (e.g., No data reported for Bihar.)' }
      - label: 'Map'
        name: 'map'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Legend Title', name: 'legend_title', widget: 'string' }
          - { label: 'Value Suffix', name: 'value_suffix', widget: 'string' }
      - label: 'Progress Bars'
        name: 'progressbars'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'State Text', name: 'state_text', widget: 'string', hint: 'The text that appears between the state name and data value on the state pages in the "related national goals" box (e.g., Bihar has achieved 192.89%)' }
      - { label: 'Last Updated', name: 'last_updated_at', widget: 'datetime', time_format: false }
      - label: 'Sources'
        label_singular: 'Source'
        name: 'sources'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
        required: false  
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'resources'
    label: 'Resources'
    label_singular: 'Resource'
    folder: '_resources/'
    create: true
    # slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    slug: '{{slug}}'
    sortable_fields: ['title', 'type', 'author', 'posted_on']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'resource' }
      - { label: 'Type', name: 'type', widget: 'select', allow_add: false,
          options: [
            'Archives',
            'Electricity',
            'Electric Mobility',
            'Energy Transition',
            'Health',
            'State Clean Energy Goal Tracker',
            'Technology'
          ],
          default: ['Archives']
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string', hint: 'https://example.com' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Publish Date', name: 'posted_on', widget: 'datetime', date_format: 'MM.YYYY', time_format: false, format: 'LLL' }
      - { label: 'Sectors', name: 'sectors', widget: 'relation', collection: 'sectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title'
        }
      - { label: 'Subsectors', name: 'subsectors', widget: 'relation', collection: 'subsectors', multiple: true,
          display_fields: [title],
          search_fields: [title],
          value_field: 'title',
        }

  - name: 'sectors'
    label: 'Sectors'
    label_singular: 'Sector'
    folder: '_sectors/'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'sector' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'sectors' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'feature_image', widget: 'image', choose_url: false, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'subsectors'
    label: 'Sub Sectors'
    label_singular: 'Sub Sector'
    folder: '_subsectors'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title', 'sectors']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'subsector' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sectors', name: 'sector', widget: 'relation', collection: 'sectors', display_fields: ['title'], search_fields: ['title'], value_field: 'title' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'states'
    label: 'States'
    label_singular: 'State'
    folder: '_states'
    create: true
    slug: '{{slug}}'
    sortable_fields: ['title', 'size', 'population']
    editor:
      preview: false
    fields:
      - { label: 'Content Type', name: 'content_type', widget: 'hidden', default: 'state' }
      - { label: 'Breadcrumbs', name: 'breadcrumbs', widget: 'hidden', default: 'states' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Featured Images'
        name: 'feature_images'
        widget: 'object'
        fields:
          - label: 'Primary'
            name: 'primary'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image', choose_url: false, required: false }
              - { label: 'Credit', name: 'credit', widget: 'string' }
          - label: 'Secondary'
            name: 'secondary'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image', choose_url: false, required: false }
              - { label: 'Credit', name: 'credit', widget: 'string' }
      - { label: 'Size', name: 'size', widget: 'string' }
      - { label: 'Population', name: 'population', widget: 'string' }
      - { label: 'Party affiliation', name: 'party_affiliation', widget: 'string' }
      - { label: 'Legislative seats', name: 'legislative_seats', widget: 'string' }
      - { label: 'Rajya seats', name: 'rajya_seats', widget: 'string' }
      - { label: 'Lok_seats', name: 'lok_seats', widget: 'string' }
      - { label: 'GDP', name: 'gdp', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'trackers'
    label: 'Trackers'
    label_singular: 'Tracker'
    extension: json
    format: json
    create: false
    editor:
      preview: false
    files:      
      - label: "Solar Tracker"
        name: "solar-tracker"
        file: "_data/national-goals/solar-performance-tracker.json"
        fields:
          - label: 'States'
            name: 'tracker'
            widget: 'list'
            allow_add: false
            collapsed: true
            fields:
              - { name: 'state' }
              - { name: 'national_contribution' }
              - { name: 'state_target' }
              - { name: 'state_achieved' }
              - { name: 'state_percentage' }
                    
      - label: "Wind Tracker"
        name: "wind-tracker"
        file: "_data/national-goals/wind-performance-tracker.json"
        fields:
          - label: 'States'
            name: 'tracker'
            widget: 'list'
            allow_add: false
            collapsed: true
            fields:
              - { name: 'state' }
              - { name: 'national_contribution' }
              - { name: 'state_target' }
              - { name: 'state_achieved' }
              - { name: 'state_percentage' }

```

**Additional context**
I'm using Jekyll v 4.3.2, ruby v3.2.2, node v20.5.0

package.json I modified the repo name just to post it in here.
```json
{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "clean": "jekyll clean",
    "clean:css": "rm -rf assets/css",
    "setup": "bundler install && npm i -y",
    "build:jekyll": "bundle exec jekyll build --incremental --limit_posts 10",
    "build:sass": "sass --no-source-map assets/_sass:assets/css",
    "build": "npm-run-all build:*",
    "watch:sass": "sass --no-source-map --watch assets/_sass:assets/css",
    "watch": "npm-run-all --parallel watch:*",
    "serve:cms": "npx npx decap-server",
    "serve:jekyll": "bundle exec jekyll serve --livereload --profile --limit_posts 3",
    "serve": "npm-run-all --parallel serve:*",
    "start": "npm-run-all --parallel watch serve"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/user/testing-repo-.git"
  },
  "keywords": [
    "decap",
    "cms",
    "jekyll",
    "sass"
  ],
  "author": "jdromero88",
  "license": "See license in LICENSE",
  "devDependencies": {
    "decap-server": "^3.0.1",
    "npm-run-all": "^4.1.5",
    "sass": "^1.64.2"
  }
}

```
