### ISSUE TITLE
Media assets not showing in the media assets manager

### ISSUE THREAD

**Issue by naturedamends** [decaporg/decap-cms#6928]
**Describe the bug**

I'm using the github backend and when uploading a image to the media assets backend, it looks like it works, but then after a refresh the image is gone from the media assets manager. The image does exist in the repository and it still works on the posts which added it. to the `public_folder` is working correct. This also dons't work if the image is just uploaded to the media asset manager and not added thought the UI in a post.

```
backend:
  name: github 
  branch: main # Branch to update (optional; defaults to master)
  repo: some/repo

media_folder: static/images
public_folder: /images

collections:
  - name: "contentpage" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
```

**To Reproduce**

- open with config
- upload a image via media assets UI or upload via repository directly
- refresh the project
- open media assets
- theres no file there

**Expected behavior**
I expect a file there

**Screenshots**
 - Decap CMS version:     "decap-cms-app": "^3.0.7",
 - Git provider: github
