### ISSUE TITLE
[i18n] duplicate field not sync

### ISSUE THREAD

**Issue by razonyang** [decaporg/decap-cms#7086]
**Describe the bug**

I have a duplicate boolean field `comments`, when changing it in one locale, the field won't sync in other locales.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/decaporg/decap-cms/assets/17720932/573d7ca9-6976-402c-bcee-19db503c9626)

**Applicable Versions:**

 - Decap CMS version: [e.g. 2.0.4]
 - Git provider: [e.g. GitHub, BitBucket]
 - OS: [e.g. Windows 7]
 - Browser version [e.g. chrome 22, safari 11]

 - Node.JS version:

**CMS configuration**

```yaml
backend:
  name: git-gateway
collections:
- create: true
  fields:
  - i18n: true
    label: Title
    name: title
    widget: string
  - i18n: true
    label: Link Title
    name: linkTitle
    required: false
    widget: string
  - default: true
    i18n: true
    label: Draft
    name: draft
    widget: boolean
  - default: false
    i18n: true
    label: Featured
    name: featured
    required: false
    widget: boolean
  - default: false
    i18n: true
    label: Pinned
    name: pinned
    required: false
    widget: boolean
  - i18n: true
    label: Date
    name: date
    picker_utc: true
    widget: datetime
  - i18n: true
    label: Description
    name: description
    required: false
    widget: text
  - collapsed: true
    field:
      label: Image
      name: image
      widget: image
    i18n: true
    label: Images
    minimize_collapsed: true
    name: images
    required: false
    summary: '{{fields.image}}'
    widget: list
  - collapsed: true
    field:
      label: Alias
      name: alias
      widget: string
    i18n: true
    label: Aliases
    minimize_collapsed: true
    name: aliases
    required: false
    summary: '{{fields.alias}}'
    widget: list
  - i18n: true
    label: Authors
    name: authors
    required: false
    widget: strings
  - i18n: true
    label: Series
    name: series
    required: false
    widget: strings
  - i18n: true
    label: Categories
    name: categories
    required: false
    widget: strings
  - i18n: true
    label: Tags
    name: tags
    required: false
    widget: strings
  - i18n: true
    label: Body
    name: body
    widget: markdown
  - i18n: duplicate
    label: Navigation Weight
    name: nav_weight
    widget: number
  folder: content/modules
  i18n: true
  label: Modules
  label_singular: Module
  meta:
    path:
      index_file: index
      label: Path
      widget: string
  name: modules
  nested:
    depth: 5
i18n:
  default_locale: en
  locales:
  - en
  - zh-hans
  - zh-hant
  structure: multiple_files
local_backend: true
locale: en
logo_url: http://localhost:7070/images/logo.png
media_folder: static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
search: true
site_url: http://localhost:7070/
```

**Additional context**

**Comment by martinjagodic** [comment]
I don't see a comments field in your config, could that be the problem?

**Comment by razonyang** [comment]
Sorry, I cut off the wrong part, updated with full configuration (maybe too long).

**Comment by razonyang** [comment]
The field will be synchronized after clicking the _Toggle i18n_ button twice.

**Comment by martinjagodic** [comment]
Could you prepare a minimum reproducible config? This one is very large so it's hard to determine the real culprit

**Comment by razonyang** [comment]
Sure.

```yaml
backend:
  name: git-gateway
collections:
- create: true
  fields:
  - default: true
    hint: Whether to show comments.
    i18n: duplicate
    label: Comments
    name: comments
    required: false
    widget: boolean
  - i18n: duplicate
    label: Nav Weight
    name: nav_weight
    widget: number
  folder: content/foo
  i18n: true
  label: Foo
  name: foo
i18n:
  default_locale: en
  locales:
  - en
  - zh-hans
  - zh-hant
  structure: multiple_files
local_backend: true
locale: en
logo_url: http://localhost:7070/images/logo.png
media_folder: static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
search: true
site_url: http://localhost:7070/
```

![decapcms-boolean-i18n-duplicate](https://github.com/decaporg/decap-cms/assets/17720932/b8ba29d9-6478-422b-a30b-a4b5ca57f054)
