### ISSUE TITLE
Gitlab PKCE auth error on Decap 3.1

### ISSUE THREAD

**Issue by kkellydesign** [decaporg/decap-cms#7093]
As of the Decap 3.1 release on February 1, Gitlab PKCE is no longer working. I've tested both Firefox and Chrome. 

When I visit /admin and try to log in, it immediately redirects me to Gitlab and shows the following screen: 

<img width="426" alt="Screenshot 2024-02-06 at 12 16 40 PM" src="https://github.com/decaporg/decap-cms/assets/202590/07993d8e-5e2c-4862-b98b-da0914067ab1">

**To Reproduce**
config.yml: 
```
backend:
  name: gitlab
  repo: my_repo # Path to your GitHub repository
  auth_type: pkce
  branch: main
  app_id: my_id
  ```
  
  admin/index.html – the link below causes the error. But changing the pinned version to `3.1.0-beta.2` fixes it.

  ```
     <script src="https://unpkg.com/decap-cms@3.1.1/dist/decap-cms.js"></script>

    <script src="/dist/js/nunjucks-slim.js"></script>
    <script src="/admin/util-bundled.js"></script>
    <script src="/admin/templates.js"></script>
    <script src="/admin/previews.js" type="text/babel"></script>
```  

**Applicable Versions:**
 - Decap CMS version: 3.1.1
 - Git provider: Gitlab PKCE auth
 - OS: mac locally.. but also on prod, with the CI running on Gitlab.
