### ISSUE TITLE
Integrating Compressor.js for image uploading optimization

### ISSUE THREAD

**Issue by privatemaker** [decaporg/decap-cms#7107]
As suggested in issue [decap-website#14](/decaporg/decap-website/issues/14), it is worth considering integrating [Compressor.js](https://fengyuanchen.github.io/compressorjs/) which appears to be a client-side JS image compression library which:

> Uses the Browser's native [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) API to do the compression work.

It is made by @fengyuanchen and is in this [repo](https://github.com/fengyuanchen/compressorjs) and seems mature and stable.

**Comment by martinjagodic** [comment]
it would be great to add this option. But first, we need to define how this should be used.

This is a config option in the media_library object or a set of options. I recall some discussions on this topic in other issues, so let's check for that also.

**Comment by samo4** [comment]
One of the guiding principles the revival of this project is "don't add dependencies unless absolutely necessary".  So in my opinion that means that we need a hook to which a mostly independent plugin can bind into.

**Comment by 4www** [comment]
I'm also all in for this feature!
As web-developer, I'm always choosing SSG + DecapCMS (gitlab backend) [huge fan, thanks so much for the hard work!].

One thing that's most missing for my clients, and fellow developers (used to Wordpress, and the likes of UX on Facebook etc.), is the image optimization/compression/resize.

My current solution is to explain to my clients, and add it into the docs/hints, to use https://squoosh.app (which is WASM frontend only) before uploading an image; but ofc this has its limits, when people want to process many files, or simply feels tedious compared to a drag-and-drop (and auto opti).

Here are a few links of similar apps that could be used (or inspirations):
- https://github.com/GoogleChromeLabs/squoosh
- https://github.com/silvia-odwyer/photon
- https://github.com/jamsinclair/jSquash
- https://github.com/dlemstra/magick-wasm
- https://github.com/sveltia/sveltia-cms/issues/352 (linked already to this issue → docs: https://github.com/sveltia/sveltia-cms#optimizing-images-for-upload)

As for UX, it feels that by default, the image widget could show a "optimize checkbox/field" (with some properties), but these tools have so many options it feels complicated to offer sane defaults and customization.

**Comment by martinjagodic** [comment]
@4www thanks for your enthusiasm! This can be a very powerful feature indeed. It can be part of the image module or a (sub)widget on its own. Would you mind drawing a UX proposal and a comparison of these libraries so we can decide on one? 

When adding new dependencies, we have to be very careful. It has to be a production-ready library with a good maintenance score. Ideally, we wouldn't need one.

**Comment by 4www** [comment]
Thanks for your reply @martinjagodic; I will work on a UX proposal and compare these libraries.
Also I will explore sveltia's implementation, to me it would be great if sveltia and decap stay 1to1 drop-in replacements of each other.

# Sveltia's approach

Dependencies:
- @jsquash/web: https://github.com/sveltia/sveltia-cms/blob/main/package.json#L36 (convert all uploaded raster images to web-p, Safari only, as other browser seem to have built-in support). 
- exifr: https://github.com/sveltia/sveltia-cms/blob/main/package.json#L44 (cleanup exif data in images)
- svgo: https://github.com/sveltia/sveltia-cms/blob/main/package.json#L62 (optimize svg)

For all browsers other than Safari, it has uses custom code to convert raster images to webp https://github.com/sveltia/sveltia-cms/tree/main/src/lib/services/utils/media/image.

Config:
- https://sveltiacms.app/en/docs/features#image-optimization
- https://sveltiacms.app/en/docs/media/internal#image-optimization
```
media_libraries:
  default:
    config:
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
          width: 2048 # default: original size
          height: 2048 # default: original size
        svg:
          optimize: true
```

# UX notes:
Sveltia made the choice to have no extra GUI elements, only CMS config.

**Comment by martinjagodic** [comment]
Not my favorite option. This means that all images are compressed to 85% quality, which can be too much or too little depending on the uploaded image.

If we add dimension editing (cropping, resizing), a visual helper would be very useful to reposition the cropped area.

Some defaults can be useful, though.

My proposal:

Dimensions
- simple cropper tool
- The developer can set fixed dimensions (or a list of them), but the user needs to have positioning control

Quality:
- format: dev can set the default, and the user can override it. We should check if there is a way to auto-determine the best format.
- compression level, in %. The dev can set the default, and the user can override it. Again, an auto-determination tool would be ideal. 

Optional:
- generate multiple sizes from one image, for instance, for mobile, desktop, retina... I would put this in the Dimensions bucket.

**Comment by 4www** [comment]
Yes I agree with your point, global config can be wrong for some situations.

- dimensions: cropping with user controls, is great
- quality: defaults that can be overridden is perfect (format + compression)
- multiple images: that's also great, for responsive images (srcset)

I think it should be noted that some SSG come with built-in image processing
- https://www.gatsbyjs.com/docs/conceptual/using-gatsby-image/
- https://gohugo.io/content-management/image-processing/
- https://nextjs.org/docs/app/getting-started/images (not sure if that works in SSG mode)

This has the advantage to respect the size of the user upload, and generate at build time what the SSG theme requires.

I also likes the approach of the "per collection media library" https://decapcms.org/docs/collection-folder/#media-and-public-folder which could come with local configuration (for collection of for image widget).

I'm thinking it might be tedious (if the UX is not right), for an end user to have to select image processing for every image that they upload.

**Comment by martinjagodic** [comment]
> I think it should be noted that some SSG come with built-in image processing

Yes, and that should be the preferred way of compressing images - when building the frontend. But on-upload is also a viable strategy, especially when storage is expensive.


> I'm thinking it might be tedious (if the UX is not right), for an end user to have to select image processing for every image that they upload.

I agree, that's why there should be a config-set default, or some automatic detection of the ideal compression. Like Cloudinary has with q:auto. Maybe this whole options menu could be in a details tag called "Advanced options" in the upload menu?

**Comment by 4www** [comment]
From a UX perspective, "defaults over decisions" should be preferred (the end user should have by default zero decision to make, only some options: resize/crop + quality); "advanced options" is a great naming choice.

Note: also not to forget, images can be uploaded from the `image` and `markdown` widgets.

**Comment by 4www** [comment]
> Note: written with the help of gpt-5; 
> Note 2: image processing, is a huge topic, with a lot of options, so trying to get a clearer picture of what is required, good to have, or too much; all fitting well with decap.
> Note 3: hooks would allow to have no hard image processing library dependency in decap; but i guess it should come with example, as different libraries must be using different options.

## Proposal Summary: Image Processing in Decap CMS

This proposal introduces **config-driven, upload-time image processing** with strong defaults, optional editor controls, and a hook-based architecture.

### Key points
- **Automatic by default**: Images are optimized on upload with no editor action required.
- **Non-technical UX**: No format or quality choices shown unless explicitly enabled.
- **Progressive disclosure**: Advanced options (crop, quality override, multiple sizes) are hidden by default.
- **Config layering**: Global → Collection → Field overrides.
- **Multiple sizes (optional)**: One upload can generate multiple derived images for advanced use cases.
- **Hook-based processing**: Image handling is done via extensible hooks, avoiding hard dependencies in core.
- **SSG-friendly**: Complements (does not replace) build-time image pipelines.

### Defaults
- `format: auto`
- `quality: auto`
- Metadata stripped
- Single optimized output
- No UI shown to editors

### Extensibility
- Plugins can implement compression, resizing, cropping, format conversion, SVG optimization, watermarking, etc.
- If no hook/plugin is present, uploads behave exactly as today.

This approach (should) improve editor UX while respecting Decap CMS’s architectural principles and dependency constraints.

```yaml
# =================================================
# PROPOSED IMAGE PROCESSING CONFIG (FULL REFERENCE)
# This is NOT current Decap CMS schema.
# It documents all proposed options and defaults.
# =================================================

# -------------------------------------------------
# Global image processing (applies everywhere)
# -------------------------------------------------
media_processing:
  enabled: true                # Master switch for upload-time image processing
  defaults:
    format: auto               # auto | jpeg | png | webp | avif
                               # auto = choose best format at upload time
    quality: auto              # auto | 1–100
                               # auto = perceptual / content-aware quality
    strip_metadata: true       # Remove EXIF / ICC / GPS metadata
    preserve_original: false   # Keep original upload alongside processed output

    max_width: null            # Resize if larger than value (px)
    max_height: null           # Maintains aspect ratio
  ui:
    mode: auto                 # auto | simple | advanced
                               # auto = hide UI unless overrides are allowed
    advanced_label: "Advanced image options"
  advanced:
    allow_user_override: true  # Allow per-image overrides in UI

# -------------------------------------------------
# Media library integration (hook-based)
# -------------------------------------------------
media_libraries:
  default:
    config:
      processing:
        hook: image             # Name of processing hook
                               # If no plugin registers this hook,
                               # uploads behave exactly as today

# -------------------------------------------------
# Collections
# -------------------------------------------------
collections:
  - name: posts
    label: Posts
    folder: content/posts
    path: "{{slug}}/index"

    # ---------------------------------------------
    # Collection-level image defaults
    # ---------------------------------------------
    media_processing:
      defaults:
        max_width: 2400         # Cap image dimensions for this collection
        max_height: 2400
        quality: auto
        format: auto
    fields:
      - label: Title
        name: title
        widget: string

      # -------------------------------------------
      # Image field (full control)
      # -------------------------------------------
      - label: Cover Image
        name: image
        widget: image
        media_processing:
          enabled: true         # Optional override (inherits global by default)

          # ---------------------------------------
          # Automatic behavior (no UI interaction)
          # ---------------------------------------
          defaults:
            role: cover         # Semantic hint for themes / plugins
            format: auto
            quality: auto
            strip_metadata: true

          # ---------------------------------------
          # Editor-facing controls (optional)
          # ---------------------------------------
          user_controls:
            crop:
              enabled: true     # Show crop UI
              free: false       # Freeform crop if true
              aspect_ratio: 16/9
              presets:
                - label: Wide
                  ratio: 16/9
                - label: Square
                  ratio: 1/1
            quality:
              enabled: true
              range: [60, 95]   # Allowed override range
              default: auto
            format:
              enabled: false    # Hide format choice for non-technical users

          # ---------------------------------------
          # Advanced / power-user options
          # ---------------------------------------
          advanced:
            generate_sizes:
              enabled: false    # Off by default
              sizes:            # Pixel widths
                - 640
                - 1280
                - 1920
              output: derived_only # derived_only | include_original

      # -------------------------------------------
      # Markdown field using image uploads
      # -------------------------------------------
      - label: Content
        name: body
        widget: markdown
        media_processing:
          defaults:
            max_width: 1600
            quality: auto
            format: auto

  # ---------------------------------------------
  # Gallery collection (editor-heavy control)
  # ---------------------------------------------
  - name: gallery
    label: Gallery
    folder: content/gallery
    media_processing:
      defaults:
        max_width: 3000
        preserve_original: true
    fields:
      - label: Image
        name: image
        widget: image
        media_processing:
          user_controls:
            crop:
              enabled: true
              free: true         # Freeform cropping
            quality:
              enabled: true
            format:
              enabled: true

# -------------------------------------------------
# Hook contract (conceptual, not YAML)
# -------------------------------------------------
# processImage(file, resolvedConfig) => ProcessedImage[]
#
# - Input: original File + merged config
# - Output: one or more processed files
# - Supports: resize, crop, format, compression,
#   EXIF cleanup, SVG optimization, watermarking
#
# No required image-processing dependency in core.
```

**Comment by martinjagodic** [comment]
Good summary, thanks. A bit over-engineered for a first iteration of this feature.

I don't understand what you mean by hooks. Can you explain in more detail or provide an example?

I would avoid plugins for now. This should only work with the built-in default media library, with the helper tool that we will choose.

This is my stripped-down version. All these settings would be in the advanced upload settings details tag under each image. I hope it makes sense. I'm not very versed in UX tools to produce a visual mock. 

```yml
# -------------------------------------------------
# Can be set in global, collection or per-field level
# -------------------------------------------------
media_processing:
  enabled: true              # Master switch for upload-time image processing
                               
  format:
    enabled: true            # false = don't change the format
    default: auto            # auto | jpeg | png | webp | avif
                               # auto = choose best format at upload time
  quality:
    enabled: true            # Enable quality settings
    range: [60, 95]          # Allowed override range
    default: auto            # auto | 1–100
                               # auto = choose best quality at upload time
  strip_metadata: true       # Remove EXIF / ICC / GPS metadata
  width: null                # Resize if larger than value (px)
  height: null               # Maintains aspect ratio
  aspect_ratio: 16_9         # Override aspect ratio
```
