### ISSUE TITLE
Error when trying to change image in gallery

### ISSUE THREAD

**Issue by tadej321** [decaporg/decap-cms#7130]
Whenever I try to change the image in a gallery of a collection the CMS throws the following error:

```
TypeError: t.getObjectValue(...).set is not a function
    at ListControl.js:163:57
    at onChange (EditorControl.js:70:48)
    at n.value (withMediaControl.js:56:9)
    at ii (react-dom.production.min.js:149:32)
    at Ai (react-dom.production.min.js:177:1)
    at ua (react-dom.production.min.js:201:16)
    at ca (react-dom.production.min.js:202:231)
    at Ka (react-dom.production.min.js:211:214)
    at Ha (react-dom.production.min.js:210:277)
    at za (react-dom.production.min.js:210:113)
```

This is my collection config:

```
collections:
  - name: "projekt" # Used in routes, e.g.,
    label: "Projekt" # Used in the UI
    folder: "projekti" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Opis", name: "description", widget: "markdown"}
      - {label: "Aktualen", name: "active", widget: "boolean", default: true}
      - {label: "Opomba", name: "disclaimer", widget: "string", required: false}
      - label: "Galerija"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        field: { label: Image, name: image, widget: image }
      - label: "Kategorija"
        name: "category"
        widget: "select"
        options: [ "Gradnje", "Nadzori" ]
```

The image extensions are jpg and jpeg
