### ISSUE TITLE
`picker_utc` of datetime widget is broken in #6980, resulting in a timezone mismatch

### ISSUE THREAD

**Issue by hangvane** [decaporg/decap-cms#7132]
**Describe the bug**

`picker_utc` is broken in #6980, that takes no effect on the behavior of processing timezone.

https://github.com/decaporg/decap-cms/commit/22370b13e49a4a5f58a60ebd4bc40ce4b141eb11#diff-93df641b502cdffd0d6642a8c06ad7ba617a16ee4907262538db0820a966a886L161

As a result, the time displayed stored are mismatched.

If I pick the current time, I will get a time that is 8 hours early (in the filename ``slug: {{day}}-{{hour}}``), and there's no way to change the behavior.

**To Reproduce**

1. Add a datetime widget
```yaml
collections:
  - name: 'Post' # Used in routes, e.g., /admin/collections/blog
    label: 'post' # Used in the UI
    folder: 'source/_posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}{{month}}{{day}}-{{hour}}{{minute}}-{{filename}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: '{{year}}-{{month}}/{{urlname}}.htm'
    fields: # The fields for each document, usually in front matter
      - {label: 'title', name: 'title', widget: 'string'}
      - {label: 'filename', name: 'filename', widget: 'string'}
      - {label: 'urlname', name: 'urlname', widget: 'string'}
      - {label: 'date', name: 'date', widget: 'datetime', picker_utc: true}
```
2. Edit the date in the UI
3. Check the front-matter and filename of the generated markdown file.

**Expected behavior**

The stored datetime string should be the same as picked.

**Screenshots**

**Applicable Versions:**

 - Decap CMS version: 3.1.1
 - Git provider: GitHub
 - OS: Windows 11
 - Browser version chrome 112

**CMS configuration**

```yaml
collections:
  - name: 'Post' # Used in routes, e.g., /admin/collections/blog
    label: 'post' # Used in the UI
    folder: 'source/_posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}{{month}}{{day}}-{{hour}}{{minute}}-{{filename}}' # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: '{{year}}-{{month}}/{{urlname}}.htm'
    fields: # The fields for each document, usually in front matter
      - {label: 'title', name: 'title', widget: 'string'}
      - {label: 'filename', name: 'filename', widget: 'string'}
      - {label: 'urlname', name: 'urlname', widget: 'string'}
      - {label: 'date', name: 'date', widget: 'datetime', picker_utc: true}
```

**Additional context**
