### ISSUE TITLE
Published content not listed in their collection UI

### ISSUE THREAD

**Issue by nhoizey** [decaporg/decap-cms#7148]
**Describe the bug**

I've published some content, they are visible on the live site, but the collection UI tells me there is no content yet.

**To Reproduce**

See configuration.

**Expected behavior**

I guess the UI should list the content.

**Screenshots**

![CleanShot 2024-03-16 at 20 41 34@2x](https://github.com/decaporg/decap-cms/assets/78213/ea84c9ff-6210-49c0-850e-9bb34678397b)

**Applicable Versions:**

 - Decap CMS version: 3.1.3
 - Git provider: GitHub (private repo)
 - Browser version: doesn't work in any browser
 - Node.JS version: 21

**CMS configuration**

Here's my collection config:

```yaml
collections:
  - name: 'blog'
    label: 'Blog'
    label_singular: 'blog'
    folder: 'src/collections/blog'
    path: '{{year}}/{{month}}/{{day}}/{{slug}}'
    slug: '{{slug}}/index'
    summary: '{{title}} ({{day}}/{{month}}/{{year}})'
    create: true
    media_folder: ''
    public_folder: ''
    view_groups:
      - label: Année
        field: date
        pattern: \d{4}
    fields:
      - label: 'Titre'
        name: 'title'
        widget: 'string'
        tagname: 'h1'
      - label: 'Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Image de couverture'
        name: 'image'
        widget: 'image'
        media_folder: ''
        required: false
        tagname: ''
      - label: 'Texte'
        name: 'body'
        widget: 'markdown'
        hint: 'Contenu du billet'
```

**Comment by nhoizey** [comment]
To add some information:

If I create a new content, I don't see it either in the collection UI, but I see it in the workflow:

![CleanShot 2024-03-16 at 20 53 24@2x](https://github.com/decaporg/decap-cms/assets/78213/aea2cd80-f6a6-4a22-af45-256db388026b)

**Comment by nhoizey** [comment]
For additional information, I discovered there an experimental support for [nested collections](https://decapcms.org/docs/collection-nested/), activated it, and the content is indeed listed in the UI:

![CleanShot 2024-03-18 at 18 10 38@2x](https://github.com/decaporg/decap-cms/assets/78213/4822a776-e41b-4d98-928a-52b69f7b47b3)

So I guess this feature could be automatically activated if the `path` and/or `slug` contains at least one `/`.

I still wish I could see the full list of contents of the collection when I didn't select any sub folder.

**Comment by Juniors017** [comment]
i have same problem, use you .md or .mdx file format ? 
have you clear your cache

**Comment by elnikkis** [comment]
Are your settings of folder, path, and slug correct? 
In my case, I had to specify the correct path pattern where the files were located or else nothing would show up.

**Comment by nhoizey** [comment]
@elnikkis I didn't answer last year, but I didn't change anything, here's my config for these:

```yaml
    folder: 'src/collections/blog'
    path: '{{year}}/{{month}}/{{day}}/{{slug}}'
    slug: '{{slug}}/index'
```
