### ISSUE TITLE
Support for the .mdx format

### ISSUE THREAD

**Issue by Juniors017** [decaporg/decap-cms#7158]
I'm using DecapCMS with Docusaurus, and like many other applications, Docusaurus utilizes .mdx files. I really wish that DecapCMS could support .mdx extensions.

**Comment by mmkal** [comment]
Proper .mdx support would be good, but for now you could use a custom formatter: https://decapcms.org/docs/custom-formatters

**Comment by Juniors017** [comment]
hi
For now, I'm using this in my collections:

```yaml
collections:
- name: docs
  label: Documentations
  label_singular: 'Documentation'
  folder: docs
  extension: "mdx" 
  format: "frontmatter"
```

It's functional.

Could you tell me more about the custom formatter? I'm not quite sure what it will bring to me. Maybe just for the preview? How do I create one for the .mdx format?
