### ISSUE TITLE
Backend for self-hosted Gitlab still queries gitlab.com

### ISSUE THREAD

**Issue by JbIPS** [decaporg/decap-cms#7168]
**Describe the bug**
I configured a backend for my hosted version of Gitlab
```yaml
  name: gitlab
  repo: web/landing
  auth_type: pkce # Required for pkce
  app_id: *******
  api_root: https://gitlab.****/api/v4
  base_url: https://gitlab.*****
  auth_endpoint: oauth/authorize
```
On login:
- I get rediricted to my hosted app :heavy_check_mark: 
- a call is made to `GET https://gitlab.*****/api/v4/projects/web%2Flanding` :heavy_check_mark: 
- then a call to `GET https://gitlab.com/api/v4/projects/web%2Flanding` :x: 

Of course the 3rd call gives a 404 and login workflow stops.

I looked at the sources but couldn't find a static ref to `gitlab.com`.

**To Reproduce**
1. Configure a backend for a hosted gitlab
2. Try to login

**Expected behavior**
No call should be made to `gitlab.com`

**Screenshots**
![Screenshot from 2024-04-09 17-50-08](https://github.com/decaporg/decap-cms/assets/2248473/4ecf1c1b-2fb7-4c17-8f7b-f50bbf0b2c40)

**Applicable Versions:**
 - Decap CMS version: 3.0.0 (https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js)
 - Git provider:Gitlab
 - OS: Fedora 39
 - Browser version: Firefox 129.0.4

**CMS configuration**
```yaml
collections:
  - name: 'posts'
    label: "Posts de blog"
    folder: "blog/posts"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre", name: "title", widget: "string"}
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Miniature", name: "thumbnail", widget: "image"}
      - { label: "Categorie", name: "categoriy", widget: "string"}
      - { label: "Résumé", name: "excerpt", widget: "markdown"}
      - { label: "Contenu", name: "body", widget: "markdown"}

locale: fr

media_folder: "assets/posts"
backend:
  name: gitlab
  repo: web/landing
  auth_type: pkce # Required for pkce
  app_id: *******
  api_root: https://gitlab.****/api/v4
  base_url: https://gitlab.*****
  auth_endpoint: oauth/authorize
```
