### ISSUE TITLE
datetime widget time picker does not accept any valid input

### ISSUE THREAD

**Issue by HastingsEngineering** [decaporg/decap-cms#7212]
**Describe the bug**
The datetime widget in time picker mode does not accept any valid input

**To Reproduce**

1. Create a datetime widget with time_format=true
2. Try to type in a time

The hours field should fill in, then upon entering the next digit, the whole widget clears

**Expected behavior**
You should be able to enter a time

**Screenshots**
Example trying to enter the time 05:30

Input: "05"
![image](https://github.com/decaporg/decap-cms/assets/121467278/593e9197-139f-46dd-9feb-c22012d2dfc6)

Input: "053"
![image](https://github.com/decaporg/decap-cms/assets/121467278/0dd67e66-9862-44db-925f-775e08703893 "After pressing '3'")

**Applicable Versions:**
decap-cms-app 3.1.10 
decap-cms-core 3.3.6
decap-cms 3.1.10
- Git Provider: Gitlab
- OS: Win10
- Firefox

**CMS configuration**
```
backend:
  name: git-gateway
  branch: main

site_url: redacted

publish_mode: editorial_workflow

# Media
media_folder: static/assets/uploads
public_folder: /assets/uploads

# File Routes
collections:     
  - label: Events
    label_singular: Event
    name: events
    folder: src/lib/site/pages/events
    path: "{{slug}}"
    slug: "{{slug}}"
    preview_path: "events/{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: blocks
      - label: Title
        name: title
        widget: string
        hint: Sets the page title in browsers and search engines
      - label: Description
        name: description
        widget: text
        hint: Gives the page a description in SEO for search engines
      - label: Start Date
        name: startDate
        widget: datetime
        date_format: YYYY-MM-DD
        picker_utc: true
      - label: End Date
        name: endDate
        widget: datetime
        date_format: YYYY-MM-DD
        required: false
        picker_utc: true
        default: ""
      - label: Start Time
        name: startTime
        widget: datetime
        time_format: true
        required: false
        picker_utc: true
        default: ""
      - label: End Time
        name: endTime
        widget: datetime
        time_format: true
        required: false
        picker_utc: true
        default: ""
      - label: All Day?
        name: allDay
        widget: boolean
        hint: If set, events will not display a time.
        default: false
      - label: Tags
        name: tags
        widget: list
```
