### ISSUE TITLE
Format ignored for datetime widget when date and time format specified

### ISSUE THREAD

**Issue by EthanLMartin** [decaporg/decap-cms#7250]
**Describe the bug**
When using the date time widget, if the date_format or time_format options are used, then the format option is ignored.

The [documentation](https://decapcms.org/docs/widgets/datetime/) specifies that "If set, date_format and time_format are not used."

**To Reproduce**
1. Create a widget using the datetime widget
2. Add the `format`, `date_format` and `time_format` options (e.g. `YYYY-MM-DDTHH:mm:ss`, `DD/MM/YYYY` and `HH:mm` respectively)
3. When publishing the content, the format is ignored and is saved as `{date_format}T{time_format}` (e.g. `DD/MM/YYYYTHH:mm` based on the above)

**Expected behavior**
As per the documentation, expected the saved format so be the overall format specified. (In the examples above this would be `YYYY-MM-DDTHH:mm:ss`)

**Screenshots**
N/A

**Applicable Versions:**
 - Decap CMS version: 3.1.11
 - Git provider: GitLab
 - OS: All
 - Browser version: All
 - Node.JS version: 20

**CMS configuration**
```
backend:
  name: test-repo
media_folder: static/images
public_folder: /images
collections:
  - label: Cross club
    name: cross-club
    files:
      - name: promotion
        label: ⚙ Promotion
        widget: object
        fields:
          - name: timedPromotions
            label: Timed promotions
            widget: list
            fields:
              - name: promotionDetails
                label: Timed promotion content
                widget: object
                fields:
                  - name: from
                    label: From
                    widget: datetime
                    format: YYYY-MM-DDTHH:mm:ss
                    dateFormat: DD/MM/YYYY
                    timeFormat: HH:mm
                  - name: to
                    label: To
                    widget: datetime
                    format: YYYY-MM-DDTHH:mm:ss
                    dateFormat: DD/MM/YYYY
                    timeFormat: HH:mm
            hint: ''
            default: []
            collapsed: true
        file: data/cross-club/club/promotion.json
```

**Additional context**
N/A
