### ISSUE TITLE
Github OAuth Not Found when accessing /admin/ from cpanel host

### ISSUE THREAD

**Issue by Raikojou** [decaporg/decap-cms#7292]
**Describe the bug**
Using Github OAuth, users can log in via [pawthefly.netlify.app/admin](pawthefly.netlify.app/admin), but when logging in via [pawthefly.com.au/admin](pawthefly.com.au/admin) it pops up a new browser that simply says "Not Found"

**To Reproduce**
1. Set up Github OAuth and Netlify OAuth by following [this link](https://docs.netlify.com/security/secure-access-to-sites/oauth-provider-tokens/)
2. visit https://pawthefly.netlify.app/admin/, click Login with GitHub, successfully logged in to Admin
3. visit https://pawthefly.com.au/admin/#/, click Login with GitHub, gets greeted by "Not Found" page

**Expected behavior**
Users to be able to login to admin from https://pawthefly.com.au/admin/#/ instead of the `netlify.app` address

**Screenshots**
![image](https://github.com/user-attachments/assets/8828e891-4e70-4884-9920-453b1047d2d3)

**Applicable Versions:**
 - decap-cms-app 3.3.3
 - decap-cms-core 3.4.2
 - decap-cms 3.3.3
 - 
 - Git provider: GitHub
 - OS: Windows 11
 - Browser version: Checked on Firefox 130 (64-bit) and Chrome 129

**CMS configuration**
```
backend:
    name: github
    repo: Raikojou/pawthefly_html # Your GitHub repository
    branch: main

media_folder: "img/uploads" # Folder for uploaded media files
public_folder: "/img/uploads" # The public URL of the media folder

collections:
    - name: "blog" # Name of the collection
      label: "Blog" # Label in the CMS
      folder: "_posts" # Folder where the blog posts are stored
      create: true # Allow users to create new posts
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }

```

**Additional Notes**
This website was created using vanilla html without any tools like 11ty or Astro, hosted on GitHub then deployed to a cpanel hosting via git.
