### ISSUE TITLE
Cannot read properties of undefined when loading decap-cms-backend-gitlab

### ISSUE THREAD

**Issue by simevo** [decaporg/decap-cms#7320]
**Describe the bug**
When I serve the attached files with a test webserver (for example `python3 -m http.server` then open http://localhost:8000) I get:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'EmotionCore')
    at universalModuleDefinition:9:127
    at universalModuleDefinition:1:1
```

**To Reproduce**

`index.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <title>Content Manager</title>
  </head>
  <body>
    <script src="https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js"></script>
    <script src="https://unpkg.com/decap-cms-backend-gitlab@^3.0.0/dist/decap-cms-backend-gitlab.js"></script>
  </body>
</html>
```

**Expected behavior**

I expected the module to load seamlessy, but it doesn't.

**Screenshots**

The UI seems to load fine though:

![image](https://github.com/user-attachments/assets/7442de37-939d-42b8-a2dd-5fb20703b6f5)

**Applicable Versions:**

 - Decap CMS version: 3.1.3
 - Git provider: -
 - OS: Debian 12 (stable)
 - Browser version: Chromium 130.0.6723.58 

**CMS configuration**

```yaml
backend:
  name: gitlab
  branch: main # Branch to update (optional; defaults to master)
  repo: tinia-euregio/tinia-website
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
```

**Additional context**

We have forked `decap-cms-backend-gitlab` as let's say `decap-cms-backend-gitlab-forked` and we were trying to load it as in:

```html
<script src="dist/decap-cms-backend-gitlab-forked.js"></script>
<script>
  CMS.registerBackend('gitlab-forked, DecapCmsBackendGitlabForked.GitLabBackend);
</script>
```

and started getting similar errors.

So I wondered "is it our fork or upstream?" and tried loading your version (I know it's not strictly required, as the gitlab backend is built-in).
