### ISSUE TITLE
Allow list block with fields

### ISSUE THREAD

**Issue by ryangittings** [decaporg/decap-cms#7322]
It'd be great to allow an empty object, so that blocks that don't require an input are still able to be added (for section-drive content management).

```
label: 'Blocks'
  name: 'blocks'
  widget: 'list'
  types:
    - label: 'Hero'
      name: 'hero'
      widget: object
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Sidebar Text', name: 'sidebar', widget: 'string', required: false }
        - { label: 'Show Simplified Suffix', name: 'simplified', widget: 'boolean', required: false }
    - label: 'Insights'
      name: 'insights'
      widget: object
```
