### ISSUE TITLE
File widget ignores its own media_folder and instead uses media_folder from the root

### ISSUE THREAD

**Issue by cshaa** [decaporg/decap-cms#7333]
**Describe the bug**
My team is working on a static web page that has a lot of images that are preprocessed by Vite. That's why we have `media_folder: "src/assets/uploads"` in the root of the config (that's where images are supposed to go). Now, we want to add the option to upload files, which should be placed directly in the `public` folder, so we used the `media_library.media_folder` property on the `file` widget – but it is ignored, and the files are uploaded to `src/assets/uploads` instead of `public/uploads`.

**To Reproduce**
1. Create the following `config.yml`:
```yaml
local_backend: false
backend:
  name: gitlab
  repo: ...
  branch: main
  auth_type: pkce
  api_root: https://gitlab.druit.org/api/v4
  base_url: https://gitlab.druit.org
  auth_endpoint: oauth/authorize
  app_id: ...
locale: cs
publish_mode: simple
media_folder: src/assets/uploads
public_folder: "#uploads"
collections:
  - ...
  - name: files
    label: Files
    folder: src/content/files
    create: true
    fields:
      - widget: file
        name: file
        media_library:
          allow_multiple: false
          media_folder: public/uploads
```
2. Go to administration > Files and uplad a file
3. See that it was uploaded to `src/assets/uploads` and not `public/uploads`

**Applicable Versions:**

 - Decap CMS version: 3.4.0
 - Git provider: GitLab

 - Node.JS version: 23.3

**Comment by FelixBrakel** [comment]
You can work around this by defining the `media_folder` and `public_folder` one level higher in the config. That is on the `field`  instead of the `media_library`. This does come with its own strange behavior though. Consider the following example

```yaml
media_folder: "public/upload"
public_folder: "/upload"
collections:
  - name: "some collection"
  - ...
    fields:
        - { label: "Title", name: "title", widget: "string" }
        - label: "Cover Image"
          name: "image"
          widget: "image"
          choose_url: false
          media_library:
            allow_multiple: false
        - label: "Articles"
          name: "articles"
          widget: "list"
          fields:
            - { label: "Title", name: "title", widget: "string" }
            - label: "PDF"
              name: "pdf"
              widget: "file"
              choose_url: false
              media_folder: "public/archive"
              public_folder: "/archive"
              media_library:
                allow_multiple: false
```

This will correctly store the PDFs in the `public/archive` folder and serve them at `/archive`. It will also correctly store any images at `public/upload` and serve them at `/upload`. However the file picker of the Cover Image will look for files at `public/archive`. 

A workaround for this on top of the first workaround is to redefine the `media_folder` and `public_folder` as `/public/upload` and `/upload` on the Cover Image field.
