### ISSUE TITLE
Nested Collections Listing

### ISSUE THREAD

**Issue by ryangittings** [decaporg/decap-cms#7384]
Having an issue since the 3.6.0 update - it's causing nested index.md files in the collection to appear in the sidebar, rather than the main pages listing - unlike 3.5.0. This is a massive regression in my opinion.

<img width="1329" alt="Image" src="https://github.com/user-attachments/assets/5f1d5bd4-d261-4d92-909a-8f72823d2309" />

**Comment by demshy** [comment]
Hi @ryangittings do you mind sharing your config for this collection (and maybe a screenshot of the file structure)?

**Comment by ryangittings** [comment]
```
local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: 'src/uploads'
public_folder: '/uploads'
editor:
  preview: false

meta: &META
  label: 'Meta'
  name: 'meta'
  widget: 'object'
  collapsed: true
  fields:
    - { label: 'Title', name: 'title', widget: 'string', required: false }
    - { label: 'Description', name: 'desc', widget: 'string', required: false }

button: &BUTTON
  label: Button
  name: button
  widget: object
  fields:
    - label: Text
      name: text
      widget: string
    - label: Link
      name: link
      widget: string
      
theme: &THEME
  label: Theme
  name: theme
  widget: select
  options: ['gray-100', 'navy-400', 'turq-100', 'gray-100']
  required: false

navigation: &NAVIGATION
  label: 'Navigation'
  name: 'eleventyNavigation'
  widget: 'object'
  collapsed: true
  fields:
    - { label: 'Key', name: 'key', widget: 'string', required: false }
    - { label: "Parent", name: "parent", widget: "relation", required: false, collection: "pages", search_fields: ["title"], value_field: "title", display_fields: ["title"] }
    - { label: 'Excerpt', name: 'excerpt', widget: 'markdown', required: false }
    - { label: 'Order', name: 'order', widget: 'number', required: false }
    - { label: 'Icon', name: 'icon', widget: 'image', required: false }

blocks: &BLOCKS
  label: Blocks
  name: blocks
  widget: list
  types:
    - label: Hero
      name: hero
      widget: object
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Image', name: 'image', widget: 'image', required: false }
        - { label: 'Decorator', name: 'decorator', widget: 'string' }
        - { label: 'Content', name: 'content', widget: 'markdown', required: false }

collections:
  - label: 'Pages'
    name: 'pages'
    folder: 'src'
    identifier_field: 'title'
    create: true
    extension: 'md'
    filter: { field: 'layout', value: 'layouts/page.njk' }
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    nested:
      depth: 10
      summary: '{{title}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/page.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - *BLOCKS
      - *NAVIGATION
      - *META
```

<img width="361" alt="Image" src="https://github.com/user-attachments/assets/5be849f5-2527-41a9-a79d-e475cd3bbd9c" />

**Comment by martinjagodic** [comment]
@ryangittings, thanks for raising this, and sorry for your trouble. This was introduced in PR #7359, which solved issue #4972. Nested collections are used in many ways, and we didn't anticipate this would impact you so severely. We also introduced this because nested collections are still flagged as beta, indicating that breaking changes are possible.

 We will find some time to put this feature under an opt-in flag.

**Comment by ryangittings** [comment]
I just think it makes no sense from a visual point of view. To have one page in the pages list seems like a bug to me - if all the other pages are on the same level? The UI only ever shows one page in this setup - which fundamentally is incorrect with the tree.

**Comment by demshy** [comment]
@ryangittings would you mind testing with the following cms build (built from the linked PR) and config settings: 
https://loquacious-bombolone-591afc.netlify.app/decap-cms.js

```
    nested:
      depth: 10
      subfolders: true
      summary: '{{title}}'
```
