### ISSUE TITLE
EDITORIAL_WORKFLOW_ERROR: content is not under editorial workflow

### ISSUE THREAD

**Issue by aaaaargZombies** [decaporg/decap-cms#7477]
**Describe the bug**

I keep getting this warning

> Failed to load entry: EDITORIAL_WORKFLOW_ERROR: content is not under editorial workflow

And can't view unpublished content, though PRs / branches are created.

Likely related to this issue with very little detail #7025 

**To Reproduce**

- Error when saving a new entry
- Unpublished entries not visible under either
  - workflows page
  - collection page

**Expected behavior**

Can create / view / edit unpublished entries

## Screenshots

Error when accessing workflows page

![Image](https://github.com/user-attachments/assets/2e8f5c0c-4972-49f9-bea4-d74f551206ee)

Branches and PRs have been created on repo

![Image](https://github.com/user-attachments/assets/5f6b91c3-8e04-4ada-9e96-31151ea9b7db)

On saving an new entry, redirects to "published" entry with no content

![Image](https://github.com/user-attachments/assets/394f8f9d-c083-4ef5-8d3e-233540e469bd)

Sometimes entries are show in collection list but with no content

![Image](https://github.com/user-attachments/assets/6a005890-4f79-45b6-b09d-9c5c7b38c952)

**Applicable Versions: 3.6.3**

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <title>Content Manager</title>
  </head>
  <body>
    <!-- Include the script that builds the page and powers Decap CMS -->
    <script src="https://unpkg.com/decap-cms@^3.6.3/dist/decap-cms.js"></script>
  </body>
</html>
```

[view code in context](https://github.com/breathe-easy-events/sheffield.breathe-easy.uk/blob/9287b267dcc4767bbaced6ecd897e1020814c9e7/src/admin/index.html#L1-L13)

**CMS configuration**

```yaml
backend:
  name: github
  repo: breathe-easy-events/sheffield.breathe-easy.uk
  branch: main
site_url: https://sheffield.breathe-easy.uk
media_folder: "src/static/img"
public_folder: "/static/img"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    folder: "src"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    folder: "src/pages"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: "This will be converted to a slug eg. 'About Us' to 'about-us' which will be used in the URL",
        }
      - {
          label: "Menu item",
          name: "menu",
          widget: "boolean",
          default: false,
          hint: "Should this page be linked to from the navigation at the top of every page?",
        }
      - {
          label: "Discription",
          name: "discription",
          widget: "text",
          hint: "Metadata for previews on social media and search engines, aim for between 50 - 150 characters",
          pattern: ["^.{25,200}$", "Must be between 25 and 200 characters"],
          required: false,
        }
      - {
          label: "Social image",
          name: "socialImage",
          hint: "Image for previews on social media and search engines, should be 1200x630px, will be ignored if no alt text is provided",
          widget: "image",
          choose_url: false,
          required: false,
        }
      - {
          label: "Social image alt text",
          name: "socialImageAlt",
          widget: "text",
          hint: "Alt text describing preview image for screen readers",
          pattern: ["^.{25,}$", "Must be atleast 25 characters"],
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
```

[view code in context](https://github.com/breathe-easy-events/sheffield.breathe-easy.uk/blob/9287b267dcc4767bbaced6ecd897e1020814c9e7/src/admin/config.yml#L1-L59)
