### ISSUE TITLE
i18n: duplicate does not work with list widget

### ISSUE THREAD

**Issue by tpluscode** [decaporg/decap-cms#7514]
**Describe the bug**

**To Reproduce**

1. Create config as below
2. Open admin panel

**Error**

```
Error loading the CMS configuration
Config Errors:
'collections[0].fields[0].i18n' must be boolean
'collections[0].fields[0]' should match case "color" schema
Check your config.yml file.
```

**Applicable Versions:**

 - Decap CMS version: 3.6.4

**CMS configuration**

```yaml
collections:
  - name: Showcases
    label: "Showcases"
    folder: "showcases"
    i18n: true
    extension: md
    widget: "list"
    create: true
    fields:
      - name: Tags
        label: Tags
        widget: list
        i18n: duplicate
```

**Additional context**
